### ISSUE TITLE
Add android as option

### ISSUE THREAD

**Issue by myrmidon-media** [fake-useragent/fake-useragent#10]
Would be great to add android as an option, for example

``` python

ua.android

```

Thanks

**Comment by dreyco676** [comment]
Can you explain the use case?

**Comment by myrmidon-media** [comment]
Hi,

Just like in the other browsers for example:

``` python

print ua.android

```

``` text
Mozilla/5.0 (Linux; U; Android 4.0.3; de-ch; HTC Sensation Build/IML74K) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30
```

**Comment by myrmidon-media** [comment]
Maybe is possible to use this:

http://www.useragentstring.com/pages/Android%20Webkit%20Browser/

**Comment by dreyco676** [comment]
Yup I understand, but does it change the output at all? Or why would you want to act like to are an android browser?

**Comment by myrmidon-media** [comment]
Well some websites content changes depending if the visitor is a mobile device or pc. So in some cases it's useful.

**Comment by dreyco676** [comment]
Oh wow... I'm an idiot I thought this was a comment on a different project of mine. No I totally agree and I think it makes sense. Sorry again.

**Comment by hellysmile** [comment]
Android User Agent can be Webkit Browser or Chrome/Opera/Firefox for Android, not sure what to implement...

Also iPhone Safari/Chrome seems to be useful...

Maybe `ua.mobile` ?

**Comment by hezhao** [comment]
`ua.mobile` or `ua.iphone` +1

**Comment by testvinder** [comment]
I would love to see a ua.random_pc because of the issue mentioned above with some websites' content changing depending if the visitor is a mobile device or pc. Thanks!

**Comment by hellysmile** [comment]
Any proposes where to scrape such kind of user agent data?

**Comment by medse** [comment]
I'm experiencing the same problem while scraping.

 I propose to gather here User-Agent lines which triggered different behaviour of the site, so we can analyse them and maybe invent the best algo to solve this.
As of now, maybe to start with at least something and experiment later, we can search for the “ Mobile” word in the string for example? I've no statistics what exactly the sites are looking for. Maybe it's iPad:) Are there web developers who know more?

One example I have:
> Mozilla/5.0 (Windows NT 5.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.116 Safari/537.36 Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10

**Comment by japborst** [comment]
This really depends on your use-case. If the website is responsive, it's likely only a function of the browser width (and yes, that can be used server side). In most cases developers would use, AFAIK, something like is done in this [SO thread](http://stackoverflow.com/questions/21741841/detecting-ios-android-operating-system). The same test can be applied on the whole list of user agents. Perhaps you'll miss some minor ones, but that's likely negligible.

**Comment by hellysmile** [comment]
there will be eventually added `ua.desktop` and `ua.mobile`

**Comment by cheng10** [comment]
Any update on the developing progress? What about separating ios and android? Like `ua.android`, `ua.ios`.

**Comment by siulkilulki** [comment]
I'm also wating for this feature.

**Comment by wangdahoo** [comment]
+1

**Comment by d3vr** [comment]
Any update on this ?

**Comment by GihanMora** [comment]
Have they added this feature? it would be really nice to have

**Comment by MAH69IK** [comment]
Hi friends!
Try my changes - https://github.com/hellysmile/fake-useragent/pull/105
With it you can use `ua.mobile` and `ua.desktop`.

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/61
