### ISSUE TITLE
fake_useragent not working on Multiprocessing Python?

### ISSUE THREAD

**Issue by digilevi2006** [fake-useragent/fake-useragent#101]
Hi Everyone,

I'm not sure if this has been solved but yes, as the title says, can't make the fake_useragent work with Multiprocessing Python, using the Process() module. I haven't tested on Pool() but it does work when the function is not on a multiprocess.

it always gives me this Error:

`fake_useragent\fake.py", line 140, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
fake_useragent.errors.FakeUserAgentError: Error occurred during getting browser`

Any idea what's going on?

Thanks.

By the way, I've tried to use this:

`ua = UserAgent(fallback=r'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36')`

but it's giving me Error:

`Error occurred during getting browser, but was suppressed with fallback.`

`TypeError: 'str' object is not callable`

**Comment by melroy89** [comment]
I hope it's solved by now using the latest release: `pip install --upgrade fake-useragent`
