### ISSUE TITLE
https://useragentstring.com/ strings are outdated

### ISSUE THREAD

**Issue by oussjarrousse** [fake-useragent/fake-useragent#109]
The list of user-agent strings on https://useragentstring.com/ is outdated.

Any idea on how to update the list on that website, and then keep it up to date?

Or maybe it is time to move to a different API provider? or host an alternative to https://useragentstring.com/.

**Comment by melroy89** [comment]
We ~~might~~ need to migrate to a new source of user-agent strings.

**Comment by melroy89** [comment]
We have recently getting more issues that users of `fake-useragent` are unpleased with the current data source. We really need to migrate soon to a new data source. Like: https://developers.whatismybrowser.com/.

However, we can't scrape that site, not even once. Since there is a huge rate limiter active on that site. Also that site will most likely block my IP. And buying the DB costs money.

**Comment by Light2Dark** [comment]
Could we use their sample user agents which is the first 10,000 rows of their actual DB?
[https://developers.whatismybrowser.com/useragents/database/](https://developers.whatismybrowser.com/useragents/database/)

Or maybe we can start compiling our own list and manually update them from time to time while we look for an API provider.

**Comment by ssmeo** [comment]
Any suggestions on how to overcome the issue with outdated useragents strings? How are you doing this personally guys?

https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ ?

**Comment by melroy89** [comment]
> https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ ?

We could use that list. It's a active list with **most used** user-agents. But it's a very small list actually. I don't know if that is really an problem...?

> Could we use their sample user agents which is the first 10,000 rows of their actual DB?
https://developers.whatismybrowser.com/useragents/database/

We could use that sample list, but the first 10.000 rows doesn't mean the first most used user-agents. So importing those records will result in the same issue, which is that those user-agent that are not used anymore and are therefore **also** Outdated. The records are orded based on their unique database ID (and not by `times_seen` for instance).

**Comment by melroy89** [comment]
I will start with updating the pip dependency packages in PR: https://github.com/fake-useragent/fake-useragent/pull/170 (EDIT: is merged now)

Then I will try to update the scraper to use https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

**Comment by lonix1** [comment]
Sometimes you don't need huge numbers of random UAs, but rather, just the latest for a certain browser.

A list of the latest UA for each browser and os: https://www.whatismybrowser.com/guides/the-latest-user-agent/

See how a similar library does it: https://github.com/jnrbsn/user-agents

**Comment by melroy89** [comment]
Code base is now ready to migrate / scraping the other data source for user-agent strings. https://github.com/fake-useragent/fake-useragent/pull/170, https://github.com/fake-useragent/fake-useragent/pull/171, https://github.com/fake-useragent/fake-useragent/pull/172 and https://github.com/fake-useragent/fake-useragent/pull/173 are merged.

Working on this issue now, see new PR: https://github.com/fake-useragent/fake-useragent/pull/174

**Comment by melroy89** [comment]
Upgrade `pip  install --upgrade fake-useragent` to get the latest version. Which should now give you more up to date user agent strings.

**Comment by melroy89** [comment]
> Any suggestions on how to overcome the issue with outdated useragents strings? How are you doing this personally guys?
> 
> https://techblog.willshouse.com/2012/01/03/most-common-user-agents/ ?

Damn.. https://techblog.willshouse.com/ is now down.
