### ISSUE TITLE
error in random using UserAgent(), python 3.9

### ISSUE THREAD

**Issue by Rishang** [fake-useragent/fake-useragent#112]
Tried:

from fake_useragent import UserAgent
agent = UserAgent()
header = {"user-agent": agent.random}

Error:

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/noobi/.local/lib/python3.9/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/noobi/.local/lib/python3.9/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

**Comment by picousse** [comment]
same here, on python 3.7

**Comment by AvetyNS** [comment]
This fixed my problem https://github.com/hellysmile/fake-useragent/pull/110

**Comment by robertsmd** [comment]
#121 fixes this
