### ISSUE TITLE
Error When Loading Fake User Agent

### ISSUE THREAD

**Issue by danuccio** [fake-useragent/fake-useragent#113]
Whenever I load fake-useragent I get the following message.

`
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/xyz/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "/home/xyz/.local/lib/python3.6/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
`

It looks similar to but different from a message another user was getting last year #100 .

**Comment by cracklejoy** [comment]
Chiming in with the same issue.  Has only creeped up in the last few days

**Comment by danuccio** [comment]
This seems to fix the issue:
https://github.com/hellysmile/fake-useragent/pull/110

**Comment by Wapiti08** [comment]
I followed the instruction from here [link](https://stackoverflow.com/questions/68772211/fake-useragent-module-not-connecting-properly-indexerror-list-index-out-of-ra). You just need to changed the line 99 in fake_useragent/utils.py  :
```
    html = html.split('<table class="w3-table-all notranslate">')[1]
```
to:
```
    html = html.split('<table class="ws-table-all notranslate">')[1]
```
It solved my problem anyway.

**Comment by greattypo** [comment]
Just started experiencing this as well. +1 Please merge #121 :)

**Comment by melroy89** [comment]
Fixed upstream: https://github.com/fake-useragent/fake-useragent
