### ISSUE TITLE
Can I only have modern UAs?

### ISSUE THREAD

**Issue by YourMan** [fake-useragent/fake-useragent#114]
Certain sites will not work right on old user agents, so I was wondering if there is a way to select a random UA, but only from a list of modern browsers, not the old ones. Or maybe at least keep it completely random, but old UAs should have a very small percentage of happening.

**Comment by durygus** [comment]
ua = UserAgent()
     browser = random.choice(ua.data_randomize)
     userAgent = sorted(ua.data_browsers[browser], key=lambda a: grp(browsers[browser], a))[-1]

**Comment by dm9pZCAq** [comment]
@durygus what is `grp` and `browsers`?

**Comment by robertsmd** [comment]
```
from fake_useragent import *
import random
ua = UserAgent()
browser = random.choice(ua.data_randomize)
userAgent = sorted(ua.data_browsers[browser], key=lambda a: grp(utils.get_browsers()[browser], a))[-1]
```
still haven't solved what `grp` is, but here's a partial solution, mostly to the `browsers` thing

also, get_browsers is broken. PR #121 fixes it.

**Comment by robertsmd** [comment]
PR #122 will provide this functionality now.

**Comment by Rapid1898-code** [comment]
Hello - i would exactly need this functionality: only get actual random user-agents
How can i get this version?
And what is the parameter for getting only actual user-agents (i am currently using UserAgent().random

**Comment by robertsmd** [comment]
@Rapid1898-code You can go to my pull request #122 and check out that code. In the pull request comments I have the shell commands to reinstall with my version.

**Comment by Rapid1898-code** [comment]
Thanks @robertsmd - yes that works fine

**Comment by melroy89** [comment]
We now support providing "browsers" as an argument. Like: `ua = UserAgent(browsers=['edge'])` does this fix your issue?

See: https://github.com/hellysmile/fake-useragent#notes


Ps. the package is not yet released, but it's in the `master` branch.

**Comment by melroy89** [comment]
Closing as duplicate of: https://github.com/fake-useragent/fake-useragent/issues/109
