### ISSUE TITLE
What is fake-useragent-ex?

### ISSUE THREAD

**Issue by raffaelemancuso** [fake-useragent/fake-useragent#123]
Hello,

is the [fake-useragent-ex](https://pypi.org/project/fake-useragent-ex) PyPi package yours?

Because the "Homepage" link redirects to this repository, and your email is listed as author. 

Or is only the [fake-useragent](https://pypi.org/project/fake-useragent) PyPi package yours, and the `fake-useragent-ex` is not yours?

Because in the latter case there's something strange.

**Comment by melroy89** [comment]
@hellysmile Can you remove https://pypi.org/project/fake-useragent-ex/ ?

**Comment by melroy89** [comment]
It's not from us, but created my Adobj. We can't remove it. You can ignore this package.
