### ISSUE TITLE
Randomly generated error. 

### ISSUE THREAD

**Issue by brokoder** [fake-useragent/fake-useragent#124]
from fake_useragent import UserAgent
 ua = UserAgent()
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "<path>python3.8/site-packages/fake_useragent/utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "<path>python3.8/site-packages/fake_useragent/utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

## steps to reproduce
- create a virtual enviorment
- install fake-useragent via pip
- enter python shell 

python version 3.8.8

## Suggestion
Could use a better exception message to convey the error if the server is down

**Comment by lht99** [comment]
I got same problem when I used on heroku

**Comment by melroy89** [comment]
Fixed upstream: https://github.com/fake-useragent/fake-useragent
