### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome

### ISSUE THREAD

**Issue by JohnPortella** [fake-useragent/fake-useragent#132]
Config:
#useragent
ua = UserAgent()
userAgent = ua.random
headers.update({ 'user-agent': userAgent })

Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "/home/jportella/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 165, in load
    browsers_dict[browser_key] = get_browser_versions(
  File "/home/jportella/.local/lib/python3.10/site-packages/fake_useragent/utils.py", line 144, in get_browser_versions
    raise FakeUserAgentError(
fake_useragent.errors.FakeUserAgentError: No browsers version found for Chrome

the problem happens only the first time you run a script

**Comment by noamo48** [comment]
Same problem. Just started occurring.

**Comment by andymathieson** [comment]
Also seeing this

**Comment by jefmenegazzo** [comment]
@JohnPortella @noamo48 @andymathieson There are two problems with the library, due to it being out of date. To solve it, just change the following lines in the **utils.py** file:

```python
Line 99 From  
html = html.split('<table class="w3-table-all notranslate">')[1]
To       
html = html.split('<table class="ws-table-all notranslate">')[1]
```
And
```python
Line 128 From 
pattern = r'\?id=\d+\'>(.+?)</a'
To      
pattern = r'id_\d+.php\'>(.+?)<\/a'
```
Another easier way to solve it is to add the following code snippet to your program:

```python
with open("/usr/local/lib/python3.9/site-packages/fake_useragent/utils.py", 'r+') as f:
        text = f.read()
        text = text.replace('w3-table-all notranslate', 'ws-table-all notranslate')
        text = text.replace("\\?id=\\d+\\'>(.+?)</a", "id_\\d+.php\\'>(.+?)<\\/a")
        f.seek(0)
        f.write(text)
        f.truncate()
```
Just need to change utils.py directory.

**Comment by noamo48** [comment]
@jefmenegazzo thanks but I just ended up creating a simple script to fetch the latest chrome user agent instead so I wouldn’t have to rely on a broken third party script

```
import requests
from bs4 import BeautifulSoup


BROWSER_BASE_PAGE = 'http://useragentstring.com/pages/useragentstring.php?name={}'
FALLBACK_USER_AGENT = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.79 Safari/537.36'


async def get_chrome_ua():
    ua_resp = requests.get(BROWSER_BASE_PAGE.format('Chrome'))
    ua_soup = BeautifulSoup(ua_resp.text, 'lxml')
    latest_ua = ua_soup.find('li')
    return latest_ua.text if latest_ua is not None else FALLBACK_USER_AGENT
```

**Comment by Jerryruc** [comment]
Thanks a lot！

**Comment by eldarmammadov** [comment]
How we can use your code @noamo48  creating another function inside this one;
```
      def get_soup_retry(url):
          ua = UserAgent(use_cache_server=False,verify_ssl=False)
          uag_random = ua.random
      
          header = {
              'User-Agent': uag_random,
              'Accept-Language': 'en-US,en;q=0.9'
          }
```

**Comment by melroy89** [comment]
Should be solved by now. Update to the latest pacakge: `pip install --upgrade fake-useragent`
