### ISSUE TITLE
Missing isolated unit-tests

### ISSUE THREAD

**Issue by jayvdb** [fake-useragent/fake-useragent#139]
When the tests are run in an isolated VM, such as used for distro packaging, the following tests fail trying to reach the network:

- `test_fake_user_agent*`
- `*update*`
- `*cache_server*`
-  `test_utils_get*`
- `test_utils_load`
- `test_fake_default_path`
- `test_fake_safe_attrs`

Tests that really need network can be marked as networking only, then they can all be skipped using something like `pytest -k 'not network'`

**Comment by melroy89** [comment]
The current tests are actually integration tests. You are looking for good unit testers that can be run fast and within isolation, without depending on external resources like the internet.

**Comment by melroy89** [comment]
I will fix the tests as well in: https://github.com/fake-useragent/fake-useragent/pull/151 (so that the tests no longer depend on internet connection)

**Comment by melroy89** [comment]
It should be fixed with version 1.0.0. Can you verify that?

Upgrade using:

```sh
pip install --upgrade fake-useragent
```

**Comment by jayvdb** [comment]
The tests all pass on Python 3.10 in an isolated VM.

I am finding a different problem with Python 3.9 - investigating and will report a new issue when I understand it.
