### ISSUE TITLE
Invalid leading whitespace

### ISSUE THREAD

**Issue by smbslt3** [fake-useragent/fake-useragent#159]
Hi.

Recently, the `fake-useragent` randomly occur error.

```python

from fake_useragent import UserAgent
UA = UserAgent()

req_headers['User-Agent'] = UA.random  
rep = requests.get(base_url, params=params, headers=req_headers)  

>>> ---> 51 rep = requests.get(base_url, params=params, headers=req_headers) 
>>> InvalidHeader: Invalid leading whitespace, reserved character(s), or returncharacter(s) in header value: ' Mozilla/4.0 (compatible; MSIE 4.5; Mac_PowerPC)'
```

I have checked out the return value of `UA.random`, it has wired whitespace
`' Mozilla/4.0 (compatible; MSIE 4.5; Mac_PowerPC)'`
__^ here is the white space

Is it just library error?
or am I have to apply `strip()` to random ua value?

I am using `1.1.0` version.

```python
import fake_useragent
print(fake_useragent.VERSION)
>>> 1.1.0
```

**Comment by melroy89** [comment]
That is indeed not ideal. I should have done `strip()` myself. To avoid this problem at your side.

**Comment by melroy89** [comment]
Version 1.1.1 solves this issue.
