### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by soggychips** [fake-useragent/fake-useragent#16]
Urllib usage does not account for proxies

If I have time, I will write a pull request, but I cannot promise. Not sure if this is something the author is aware of, so issue created.

**Comment by hellysmile** [comment]
Nice idea, welcome

**Comment by hellysmile** [comment]
@soggychips any plans to make pull request with proxies support? For example via `os.environ` like `FAKE_USERAGENT_PROXY`?

**Comment by hellysmile** [comment]
any volunteers? @pcinkh are You interested?

**Comment by hellysmile** [comment]
I am considering to make next major release with requests as transport, it will `os.environ` proxies support out of the box. Ill post update here

**Comment by melroy89** [comment]
Is no longer needed with https://github.com/fake-useragent/fake-useragent/pull/151, since the data is stored locally within the package data.
