### ISSUE TITLE
[Bug?] user_agents in Opera contains IE user_agents

### ISSUE THREAD

**Issue by Light2Dark** [fake-useragent/fake-useragent#165]
After inspecting the user_agents used in `data/browsers.json`, I notice that there are Internet Explorer user agents under Opera.

```
# browsers.json in "internet explorer"
"internet explorer": [
        "Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; AS; rv:11.0) like Gecko",
        "Mozilla/5.0 (compatible, MSIE 11, Windows NT 6.3; Trident/7.0;  rv:11.0) like Gecko",
        "Mozilla/5.0 (compatible; MSIE 10.6; Windows NT 6.1; Trident/5.0; InfoPath.2; SLCC1; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729; 
         .NET CLR 2.0.50727) 3gpp-gba UNTRUSTED/1.0",
        ...
]
```

```
# browsers.json in "opera"
"opera": [
        ...,
        "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; ja) Opera 11.00",
        "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; en) Opera 11.00",
        "Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; pl) Opera 11.00",
       ...
]
```

This is causing some issues as some websites do not support IE anymore.

**Comment by melroy89** [comment]
yea, the strings are too old. It's actually a valid Opera user agent string. But nobody is using MSIE 8.0 and/or Windows NT anymore.

This will be fixed if we update to a newer data source. Related: https://github.com/fake-useragent/fake-useragent/issues/109

**Comment by melroy89** [comment]
Upgrade `pip  install --upgrade fake-useragent` to get the latest version. Which should now give you more up to date user agent strings.
