### ISSUE TITLE
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11

### ISSUE THREAD

**Issue by ghost** [fake-useragent/fake-useragent#167]
I read this error on closed questions, and I realized that the problem is fake_useragent, so can you please help me solve the error and run the code

**Comment by ghost** [comment]
if needed, I'm trying to run this code. https://github.com/Plasmonix/Netflixer

**Comment by melroy89** [comment]
@Hironotori That project should update their dependency to the latest package v1.1.1: https://github.com/fake-useragent/fake-useragent/releases

They need to update line 4 here: https://github.com/Plasmonix/Netflixer/blob/main/requirements.txt#L4

**Comment by melroy89** [comment]
I created a PR at there site: https://github.com/Plasmonix/Netflixer/pull/25

**Comment by YashvirGaming** [comment]
@melroy89   dude you aware now netflix has recaptcha v3 on their site
could you add that into the config as your config is mainly for Netflix.com direct login page 
this ain't no api 

BTW add more captures like I did
![image](https://github.com/fake-useragent/fake-useragent/assets/64865096/4e261dd6-804b-4697-a914-3e1347b30566)
