### ISSUE TITLE
I used this module, but it doesn't work. Every time it runs, it's the real agent information

### ISSUE THREAD

**Issue by stevenhubhub** [fake-useragent/fake-useragent#169]
options = Options()
ua = UserAgent()
options.add_argument(f'user-agent={ua.random}')
driver = uc.Chrome(chrome_options=options, headless=False, use_subprocess=True)
driver.maximize_window()
start = time.perf_counter()
driver.get('https://whatsmyos.com/')
print("userAgent: "+driver.execute_script("return navigator.userAgent;"))

Basic env info:
python3.9.2
real os info: Windows 11
real browser: chrome 110.*

This is the output message(it does not change and is my real using info): 
userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36

Thanks!

**Comment by melroy89** [comment]
What does `ua.random` in isolation gives you?

**Comment by stevenhubhub** [comment]
> 



> What does `ua.random` in isolation gives you?

Thanks for your reply, sorry, this is not a bug, through your reminder suggestion, I used print(ua.random) for debugging, it works well!

I checked my code and found a syntax error. Here is the corrected code:
options = Options()
ua = UserAgent()
print(ua.random)
options.add_argument(f'--user-agent={ua.random}')
driver = webdriver.Chrome(chrome_options=options)
driver.maximize_window()

There are 2 reasons for not working in the first above condition:
1, my syntax is wrong at options.add_argument(f'--user-agent={ua.random}'),  I left out -- when adding chrome arguments;
_--user-agent 	A string used to override the default user agent with a custom one_

2, I am not using the native webdriver, using undetected_chromedriver, I changed to the native webdriver, it works perfectly (including the display on the https://whatsmyos.com/ website), very powerful tool, Different agents are randomly generated

About why the use of undetected_chromedriver does not work, the reason I do not know for the time being, but I am ready to check its source code, it is also open source, see if you can make both perfectly compatible, if you can that would be even better!

**Comment by stevenhubhub** [comment]
> What does `ua.random` in isolation gives you?

For the second reason, I am clear now, because undetected_chromedriver rewrote user-agent, so it caused the failure, I will try to put a code submit to undetected_chromedriver, if it can pass, Then the two are perfectly compatible.
