### ISSUE TITLE
Add random_browser & random_mobile

### ISSUE THREAD

**Issue by boogheta** [fake-useragent/fake-useragent#17]
It would be useful to be able to use the very nice "random" behavior but ensure to always or never get a useragent corresponding to a mobile device

**Comment by hellysmile** [comment]
Can You give me an example when "random" returned mobile device?

**Comment by hellysmile** [comment]
Also we were talking about mobile devices https://github.com/hellysmile/fake-useragent/issues/10 and I do not know where to get list of mobile device headers.

**Comment by boogheta** [comment]
ah! interesting! I assumed there were some mobile agents returned as I'm using the random agent to do some urls redirection resolving and some twitter urls strangely returned mobile.twitter.com ones, so I guessed it came from the useragents but maybe not in the end. let me investigate a bit more and get back to you!

**Comment by boogheta** [comment]
All right, forget I said anything! For some weird reason, Twitter actually returns a noscript markup in each page that provides a redirect url to its mobile version. i'll just deactivate collecting redirect url from noscript parts
Thanks for the prompt answer!
