### ISSUE TITLE
Browser version in browsers.json is too old

### ISSUE THREAD

**Issue by pooneyy** [fake-useragent/fake-useragent#178]
The version of the edge browser in browsers.json is too old. Where else is anyone using the 18.19582 Edge browser these days. Suggest you update the browser version in browsers.json

**Comment by melroy89** [comment]
yea I know. I was busy in this PR: https://github.com/fake-useragent/fake-useragent/pull/174

**Comment by melroy89** [comment]
Upgrade `pip  install --upgrade fake-useragent` to get the latest version. Which should now give you more up to date user agent strings.
