### ISSUE TITLE
Showing "list index out of range" again and cannot be fixed by reinstalling

### ISSUE THREAD

**Issue by tailintalent** [fake-useragent/fake-useragent#18]
Hi when I type in the commands:

```
from fake_useragent import UserAgent
ua = UserAgent()
```

It shows the following error:

> Traceback (most recent call last):
>   File "scraper.py", line 287, in <module>
>     ua = UserAgent()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/fake.py", line 10, in **init**
>     self.data = load_cached()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 140, in load_cached
>     update()
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 135, in update
>     write(load())
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 92, in load
>     browsers_dict[browser_key] = get_browser_versions(browser)
>   File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fake_useragent/utils.py", line 55, in get_browser_versions
>     html = html.split('<div id=\'liste\'>')[1]
> IndexError: list index out of range

I tried uninstalling and reinstalling using `pip install fake-useragent`, but the error still shows. Could you have a look and see what is the problem?
Thanks!

**Comment by Markus-** [comment]
Hello,

I have no clue how to update the code in this repository, but it seems that there is a change in both the URL and of the HTML-content of http://www.useragentstring.com/.

If I checked it out correctly you just have to change two lines of code.
settings.py:
Line 10 
BROWSER_BASE_PAGE = 'http://useragentstring.com/pages/useragentstring.php?name=%s'

utils.py
Line 56  
browsers_iter = re.finditer(r'\?id=\d+\'>(.+?)</a', html, re.UNICODE)       

Can anybody update this version?

Regards
Markus

**Comment by hellysmile** [comment]
Give me a moment

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/commit/c30f417a34801898fd90cd0f4b326cdd398bef9f

Done! Thanks!

New version pushed to the PyPi
