### ISSUE TITLE
Visual Code error:  Import fake_useragent could not be resolved

### ISSUE THREAD

**Issue by haar-making** [fake-useragent/fake-useragent#194]
Python 3

Need to use fake_useragent but this line doesn't seem to work:
> from fake_useragent import UserAgent

I've deleted and reinstalled fake_useragent, and then upgraded it to the latest version but it isn't recognised.

I'm following the code example here:
> https://stackoverflow.com/questions/38785877/spoofing-ip-address-when-web-scraping-python

Looking at the source code there is this:
> class FakeUserAgent:

Should I be using this instead?

**Comment by melroy89** [comment]
No.. What is your error message? You don't show what is not working..

You first need to install fake useragent via: `pip3 install fake-useragent`

**Comment by haar-making** [comment]
Sorted it now.  Thanks for responding.

**Comment by haar-making** [comment]
Sorted now.  Thanks for responding.
