### ISSUE TITLE
 no module named 'fake_useragent.data'

### ISSUE THREAD

**Issue by minghuiclark** [fake-useragent/fake-useragent#206]
Hello,

I've encountered an issue while using this module. When I attempted to package it into an exe file using version 1.2.1, an error message appeared, stating that the 'fake_useragent.data' module could not be found. However, the module operates normally in the .py file. I tried downgrading to version 1.1.1, and the issue was resolved. Could you please provide guidance on how to fix this?

Thank you for your response.

**Comment by SecorD0** [comment]
Hello!
As an intermediate solution, you can add the `browser.json` file inside the EXE when building it by adding an option to the `pyinstaller` command:
```sh
pyinstaller app.py -Fn app --add-binary "venv/Lib/site-packages/fake_useragent/data;fake_useragent/data"
```

**Comment by minghuiclark** [comment]
It works. Thank you.
