### ISSUE TITLE
Service is down

### ISSUE THREAD

**Issue by rafaelcapucho** [fake-useragent/fake-useragent#21]
Returning 404

http://pastebin.com/raw/LKpiWimh

**Comment by hellysmile** [comment]
A lot of things depends on remote services and they can be down from time to time. I have an idea create simple server and host it somewhere on heroku, which for example each 12 downlods all required pages and then change fake-useragent to use hosted solution as fallback. What do You think about it?

PS: Ive just reloaded travis build and it is green

**Comment by rafaelcapucho** [comment]
Sounds great!

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/pull/33

fixes, new release in 10 min

**Comment by rafaelcapucho** [comment]
@hellysmile thank you mate
