### ISSUE TITLE
在multiprocessing.Process中会出现[ WARNING] fake.py:171 - Error occurred during getting browser: getstate, but was suppressed with fallback.

### ISSUE THREAD

**Issue by sticktoFE** [fake-useragent/fake-useragent#227]

**Comment by melroy89** [comment]
Getstate is not a valid browser. See Readme how to use this python module.

**Comment by melroy89** [comment]
Did you just try to run:

```py
from fake_useragent import UserAgent
ua = UserAgent()

print(ua.random)
```

**Comment by kostaJobCloud** [comment]
I've tried that and it didn't work.

**Comment by melroy89** [comment]
Well, of course first run: `pip install --upgrade fake-useragent`

If it doesn't work.. I need more info, please put the output / error you seeing into this ticket. Which platform are you using? Which Python version? OS? give me more info..
