### ISSUE TITLE
Error with EXE compiled with Pyinstaller 

### ISSUE THREAD

**Issue by lomanq** [fake-useragent/fake-useragent#235]
Hi, in version 1.2.0, 1.2.1, 1.3.0 of fake-useragent, i compile my application from PY to EXE with Pyinstaller. When i launch the EXE, the prompt CMD closed immediatly after show this error.

![error](https://github.com/fake-useragent/fake-useragent/assets/13378668/3596dbdc-b634-46a0-acf2-23814887c4f8)

If i use version 1.1.3 of fake-useragent, the prompt CMD shows the same error, but it not close and app works well. How can i resolve this issue?

**Comment by lomanq** [comment]
resolved with
pyinstaller --onefile --collect-datas=fake_useragent myprg.py

**Comment by Lettie69** [comment]
> resolved with pyinstaller --onefile --collect-datas=fake_useragent myprg.py

Saved my day, thank you so much!
