### ISSUE TITLE
Support for Python 3.12

### ISSUE THREAD

**Issue by raffaelemancuso** [fake-useragent/fake-useragent#238]
Deprecation warning when using Python 3.12:

```
[ABRIDGED]/site-packages/fake_useragent/utils.py:14: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import resource_filename
```

**Comment by melroy89** [comment]
Intresting. Since the code on python 3.10 and higher shouldn't use this

**Comment by melroy89** [comment]
Thanks it should work now after PR: https://github.com/fake-useragent/fake-useragent/pull/232

new release will be coming soon.
