### ISSUE TITLE
Filter on date

### ISSUE THREAD

**Issue by cp2587** [fake-useragent/fake-useragent#24]
Hello,

Thank you for the nice module. A nice addition to this library would be the ability to filter the user agent based on their release date (so that you dont get too old browser). Sadly, it seems http://useragentstring.com/ doesn't provide this kind of information. Another thing is that it seems most of the UA seems out of date on the website (exemple, for chrome, last version on  useragentstring.com is 41 when in reality it is 52..). I tried to look around to find an up-to-date database of all user-agent but i kind of failed :( Does anyone know where we could gather/scrape this data ?

The best i could found is: https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

**Comment by hellysmile** [comment]
http://useragentstring.com/ is down, I am looking for new source, Your help is appreciated
