### ISSUE TITLE
Useragentstring.com throws 404

### ISSUE THREAD

**Issue by flrs** [fake-useragent/fake-useragent#25]
Hi @hellysmile!

Thank you for this nice library, it is a really nice addition to the community! Today I tried to use the library but got stuck when it tried to connect to [http://useragentstring.com/pages/Chrome/](http://useragentstring.com/pages/Chrome/).

It seems as if that page throws a 404. I have checked through the [Wayback Machine](https://web.archive.org/web/20160413084938/http://useragentstring.com/pages/Chrome/) and it seems as if that page existed in the past. My guess is that useragentstring.com changed their website architecture.

If you believe the site was down temporarily and everything works as expected then please mark this issue as solved.

Thank you so much!

**Comment by hellysmile** [comment]
``` bash
pip install -U fake-useragent
```

That was solved. It seems You are using old version...

**Comment by flrs** [comment]
Alright, error on my side, sorry!
Thanks for your quick response!
