### ISSUE TITLE
How to get user headers for mobile useragent？

### ISSUE THREAD

**Issue by GreenJoson** [fake-useragent/fake-useragent#251]
Doesn't it support mobile, similar to UA for various cell phones

**Comment by melroy89** [comment]
Our data source doesn't have mobile UAs too bad. See also: https://github.com/fake-useragent/fake-useragent/issues/61#issuecomment-1664213268

**Comment by melroy89** [comment]
Fixed by: https://github.com/fake-useragent/fake-useragent/pull/290

**Comment by melroy89** [comment]
See the new release: https://github.com/fake-useragent/fake-useragent/releases/tag/1.5.0
