### ISSUE TITLE
Please add mobile user agents also

### ISSUE THREAD

**Issue by komalsinghgurjar** [fake-useragent/fake-useragent#261]

**Comment by komalsinghgurjar** [comment]
I want to generate user agents for android, iPhone, tablet, etc pls add

**Comment by melroy89** [comment]
Duplicate https://github.com/fake-useragent/fake-useragent/issues/251

**Comment by melroy89** [comment]
Fixed by: https://github.com/fake-useragent/fake-useragent/pull/290

**Comment by melroy89** [comment]
See the new release: https://github.com/fake-useragent/fake-useragent/releases/tag/1.5.0

**Comment by melroy89** [comment]
You can try to latest version now (2.0.0). Update via:

```sh
pip install --upgrade fake-useragent
```
