### ISSUE TITLE
Useragentstring.com change causing 404

### ISSUE THREAD

**Issue by diogommartins** [fake-useragent/fake-useragent#27]
Apparently the site isn't responding to requests to `'http://useragentstring.com/pages/%s/'` anymore, causing an initialization of UserAgent to raise a 404 error.

**Comment by hellysmile** [comment]
Hey! What version are You using?

That was solved! Try to update!

https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/settings.py#L14

**Comment by diogommartins** [comment]
Yeah... my bad! I'm using an older version :(
