### ISSUE TITLE
fake_useragent.errors.FakeUserAgentError: ('Data list is empty', None)

### ISSUE THREAD

**Issue by Zhaobo0119** [fake-useragent/fake-useragent#278]
Use pyinstaller to package and run the program, fake-useragent will prompt：

Traceback (most recent call last):
  File "fake_useragent\fake.py", line 56, in __init__
  File "fake_useragent\utils.py", line 52, in load
fake_useragent.errors.FakeUserAgentError: ('Data list is empty', None)

The reason is that browsers.json cannot be found

**Comment by melroy89** [comment]
https://github.com/fake-useragent/fake-useragent/issues/235
https://github.com/fake-useragent/fake-useragent/issues/206

**Comment by melroy89** [comment]
See also: https://github.com/fake-useragent/fake-useragent/issues/155#issuecomment-1336502286
