### ISSUE TITLE
Installation guide?

### ISSUE THREAD

**Issue by GitTheHellOutaHere** [fake-useragent/fake-useragent#28]
How about a SIMPLE **_how to install_** guide for those of us who need it?

I don't mind copying & pasting Terminal commands, but I don't script.

**Comment by hellysmile** [comment]
pip is actually standard of installation in the Python ecosystem. Do You experiencing any issues with installation via pip?

**Comment by GitTheHellOutaHere** [comment]
To me, Python is a snake. 🐍 And pip is picture-in-picture. 🖼

I wanted to install it on my Mac because of Safari's inability to retain the user agent settings I choose.
I know Terminal commands can be used to assign user agents, but they won't randomize.

I know Python scripts can be run in Terminal, so I was asking for step-by-step instructions how to run them, or else an executable script that's click-and-go.

**Comment by hellysmile** [comment]
You must learn how to use https://en.wikipedia.org/wiki/Pip_(package_manager)
It is standard of distribution of Python packages

**Comment by GitTheHellOutaHere** [comment]
After reading the pip site, I can tell this is a helluva lot more involved than I'm willing to tackle, and definitely _way_ more complicated than it should be for what it does.

Firefox and Chrome can do it with extensions, and Safari should too. I get that maybe Apple has locked up Safari making it difficult to do certain things. So why not a "simple" app then?

Apple has also locked up the OS with SIP, making it more difficult to do certain things, but it was still relatively easy to install cDock to control the appearance of my Dock.
I have a simple app to change DNS servers, and a simple app to connect to VPN servers around the world. And then of course I have Tor, a complete browser that's simple to install and use.

But in order to randomize user agents in Safari I'm expected to install one package which enables me to install another package which then allows me to install fake-useragent?

No way am I gonna clutter up my system with all that ancillary "junk."
It's not like I'm gonna have some fantastic video production suite or even Photoshop when I'm done. After all that effort all I'd have is the ability to change user agents. No thanks.

**Comment by hellysmile** [comment]
This package is just of the billion Python packages, nothing more. 99.99% Python packages uses pip.
