### ISSUE TITLE
Browser stats page down [503]

### ISSUE THREAD

**Issue by coffenbacher** [fake-useragent/fake-useragent#29]
http://www.w3schools.com/browsers/browsers_stats.asp

**Comment by victorstewart** [comment]
ditto

**Comment by hellysmile** [comment]
Hmmm, it is down for a while. I hope website will be up and running soon, if no I'll implement something like https://github.com/hellysmile/fake-useragent/issues/21#issuecomment-236392948 in 1 day or 2 to keep libriary working.

**Comment by hellysmile** [comment]
w3schools is working fine right now
https://travis-ci.org/hellysmile/fake-useragent/builds/173590047
