### ISSUE TITLE
Meaningful error message if get() reaches HTTP_RETRIES

### ISSUE THREAD

**Issue by philonor** [fake-useragent/fake-useragent#30]
I'm using `fake-useragent` in combination with [scrapy-fake-useragent](https://github.com/alecxe/scrapy-fake-useragent) and due to [useragentstring.com downtimes](https://github.com/hellysmile/fake-useragent/issues/4) this library's `get()` method yields a `socket.timeout: timed out`.

It would be nice to have a distinct exception type, e.g. `FakeUserAgentError`, which says something like `Url {0} unreachable` [instead](https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/utils.py#L32).

**Comment by hellysmile** [comment]
Thanks, I know issue. Working on new release, which never fails.
Nice idea about exceptions. I'll do this soon

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/pull/33 fixes

``fake_useragent.FakeUserAgentError`` added

new release in 10 min
