### ISSUE TITLE
spaces at end of user agent string break httpx

### ISSUE THREAD

**Issue by ajkessel** [fake-useragent/fake-useragent#307]
See discussion [here](https://github.com/encode/httpx/issues/1640). Is there a reason all the user-agents in browser.json end with a space? They are causing httpx to raise exceptions.

**Comment by melroy89** [comment]
No that's not on purpose. Thanks for informing us. 

@BoudewijnZwart this is not good I believe. Should we strip those spaces, right?

**Comment by BoudewijnZwart** [comment]
Ah, no there should not be. I will take a look at it.

**Comment by melroy89** [comment]
I will create a new patch release soon.

**Comment by melroy89** [comment]
@ajkessel Try to upgrade to version 1.5.1: `pip install --upgrade fake-useragent`

**Comment by ajkessel** [comment]
That fixes it. Thanks!
