### ISSUE TITLE
ModuleNotFoundError: No module named 'fake_useragent'

### ISSUE THREAD

**Issue by litalxh** [fake-useragent/fake-useragent#332]
![image](https://github.com/fake-useragent/fake-useragent/assets/125341557/8aa6a7d7-7fb8-421f-94a9-c6b64f781088)
as the picture show, there is an issue that can't found fake_useragent,but it actually has been installed.

**Comment by ralienpp** [comment]
How did you install it? What gives you confidence that the installation was successful?

**Comment by Hammad-AlQuraishi** [comment]
Similar issue here. Proof that the module is installed (I did an uninstall and re-install just to be sure)
![1](https://github.com/fake-useragent/fake-useragent/assets/104589055/2dab0f77-675f-4a41-9d98-45da324107a1)
![2](https://github.com/fake-useragent/fake-useragent/assets/104589055/8d1d272a-3bd4-455d-995f-00dead2e92a6)

Paths in my sys.path:
![3](https://github.com/fake-useragent/fake-useragent/assets/104589055/8467e325-60ab-4b1a-81f6-3419ff96eab0)

**Comment by melroy89** [comment]
> as the picture show, there is an issue that can't found fake_useragent,but it actually has been installed.

Are you sure you activated the virtual Python environment first and install the package inside the Python virtual env? https://docs.python.org/3/tutorial/venv.html


And if you later come back (e.g after a restart of your PC) you need to activate the virtual Python environment each time. Well, that is how Python works too bad.
