### ISSUE TITLE
Error occurred during getting broswer

### ISSUE THREAD

**Issue by rjbcollege** [fake-useragent/fake-useragent#339]
Whether trying to get user-agent string, random (or any specified browser), or getting a browser, (any) I always get the following error when stepping through code:-

`Error occurred during getting browser: iter, but was suppressed with fallback.`

This was when running the sample code under Usage and User-agent Python Dictionary.

Interstingly, when stepping through the code the error returns after every line having an attempt to print(ua.chrome) - (or whatever browser) but when running without stepping, there are no errors.

So why is it getting an error when stepping through code, even though it appears to have actually worked before getting the error?  This will potentially make debugging trickier than necessary.

For clarity, here is the actual code used:
```
import requests
from fake_useragent import UserAgent

ua = UserAgent()

# Get a random browser user-agent string
print(ua.random)

# Or get a user-aganet string from a specific browser
print(ua.chrome)
# Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
print(ua.google)
# Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_4) AppleWebKit/537.13 (KHTML, like Gecko) Chrome/24.0.1290.1 Safari/537.13
print(ua['google chrome'])
# Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
print(ua.firefox)
# Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0
print(ua.ff)
# Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0
print(ua.safari)
# Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

ua.getChrome
```

Output when run (OK):-
`Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/116.0.1938.79 Version/17.0 Mobile/15E148 Safari/604.1
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0 Config/92.2.7601.2
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Mozilla/5.0 (iPad; CPU OS 17_0_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1
`

Output when stepping (Problematic):-
`Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Linux; Android 8.1.0; Moto G (4)) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36 PTST/240201.144844
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
Error occurred during getting browser: iter, but was suppressed with fallback.
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
Error occurred during getting browser: iter, but was suppressed with fallback.
Error occurred during getting browser: iter, but was suppressed with fallback.`

I am running:-
Windows 11
MS Visual Studio Code version 1.91.1 
Python 3.12.3
fake-useragent version 1.5.1

**Comment by melroy89** [comment]
I think with "Stepping" you mean debugging the code via VSCode or?

There might be a KeyError or an IndexError, which triggers this error message "but was suppressed with fallback"...

https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L126C17-L126C25

I suspect `self.data_browsers` is empty, and causing this error. I might also add a better error message to the console log.

Maybe when you try to debug (stepping) the Python code can't find and/or load the browsers.json file anymore: https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/utils.py#L17


Causing the code to freak out on this lambda method with this iterator (iter) inside the `_filter_useragents` method:

https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L80

**Comment by melroy89** [comment]
No follow-up?
