### ISSUE TITLE
No `platforms` argument

### ISSUE THREAD

**Issue by Skumko** [fake-useragent/fake-useragent#340]
I specifically need only PC User Agents for a project and even with the latest version the `platforms` argument did not work, saying it is unknown. You have it documented as supported in the PyPI project description. I have the latest 1.5.1 version.

Example:

`ua = UserAgent(platforms="pc")`

Error: 
_TypeError: FakeUserAgent.__init__() got an unexpected keyword argument 'platforms'_

**Comment by Skumko** [comment]
Did you just drop the feature and I missed it in the Changelog ?

**Comment by melroy89** [comment]
That is strange. No we didn't remove it. Here as you can see in the code, it's there: https://github.com/fake-useragent/fake-useragent/blob/5952ee07f2a662a8724a6f0cbae208e1cb3627e3/src/fake_useragent/fake.py#L16C9-L16C18

**Comment by melroy89** [comment]
I think you are not installing the pip package correctly or use the latest version... Try: `pip install --upgrade fake-useragent`

Also be sure if you are using virtual Python environments, to activate the Python environment first..


```bash
~/demo_python took 34ms 
❯ python -m venv .

~/demo_python took 10ms 
❯ source bin/activate

~/demo_python via 🐍 v3.12.3 (demo_python) took 8ms 
❯ pip install fake-useragent
Collecting fake-useragent
  Using cached fake_useragent-1.5.1-py3-none-any.whl.metadata (15 kB)
Using cached fake_useragent-1.5.1-py3-none-any.whl (17 kB)
Installing collected packages: fake-useragent
Successfully installed fake-useragent-1.5.1

~/demo_python via 🐍 v3.12.3 (demo_python) took 11s973ms 
❯ python
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fake_useragent import UserAgent
>>> 
>>> ua = UserAgent(platforms='mobile')
>>> ua.random
'Mozilla/5.0 (Android 11; Mobile; rv:123.0) Gecko/123.0 Firefox/123.0'
>>> ua.random
'Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Mobile Safari/537.36'
>>> ua.random
```

**Comment by Skumko** [comment]
Thanks a lot for the response. As it turns out, this, among a few other issues, is the doing of Visual Studio Code not correctly recognizing different virtual environments. You are correct, it does work as intended. Thanks for the clarification.

**Comment by melroy89** [comment]
Great to hear this!

**Comment by melroy89** [comment]
Ps.. You can also check the version runtime in the future if you want, via:

```py
import fake_useragent
print(fake_useragent.VERSION)
```

**Comment by melroy89** [comment]
You can try to latest version now (2.0.0). Update via:

```sh
pip install --upgrade fake-useragent
```

The new options for `os` are: `desktop`, `mobile` and `table`. But please update first.
