### ISSUE TITLE
Why do fake-useragent and nameko conflict?

### ISSUE THREAD

**Issue by ponponon** [fake-useragent/fake-useragent#342]
The bug can be reproduced in the following way

```shell
pip install nameko
pip install fake_useragent
```

Save the following file as `tt.py`

```python
from nameko.timer import timer
from nameko.rpc import rpc, RpcProxy
from nameko.events import EventDispatcher, event_handler
from fake_useragent import UserAgent


class ProductorService:
    name = 'productor_service'

    ua_object = UserAgent(platforms=["pc"])

    @timer(1)
    def say_hi(self):
        pass

```

Run the program using the following command

```shell
nameko run --config config.yaml tt
```

The following results are obtained

```log
╰─➤  nameko run --config config.yaml tt                                                                                                            
Error occurred during getting browser: namekoentrypoints, but was suppressed with fallback.
starting services: productor_service
```

**Comment by melroy89** [comment]
Never heard of nameko to be honest.

What does the `tt` do in the `nameko run` command?

Also I do not see you are actually calling anything like `ua_object.random` or `ua_object.chrome`, which is kinda strange. It seems like Nameko is executing `ua_object.namekoentrypoints` somehow on the class. Meaning this line of code is getting executed in Nameko:

https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L147

Or:

https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L152

**Comment by ponponon** [comment]
> Never heard of nameko to be honest.说实话，从来没有听说过滑子。
> 
> What does the `tt` do in the `nameko run` command?`nameko run`命令中的`tt`有何作用？
> 
> Also I do not see you are actually calling anything like `ua_object.random` or `ua_object.chrome`, which is kinda strange. It seems like Nameko is executing `ua_object.namekoentrypoints` somehow on the class. Meaning this line of code is getting executed in Nameko:另外，我没有看到你实际上正在调用诸如`ua_object.random`或`ua_object.chrome`之类的东西，这有点奇怪。看起来 Nameko 正在类上以某种方式执行`ua_object.namekoentrypoints` 。这意味着这行代码正在 Nameko 中执行：
> 
> https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L147
> 
> Or: 或者：
> 
> https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/src/fake_useragent/fake.py#L152

nameko is a program framework, tt.py can be understood as a piece of business code (a minimal piece of code written to test nameko and fake-useragent compatibility, no real meaning, just to repeat the problem)

In principle, I should have asked nameko's author about this, but the framework has not been updated for many years and the author of nameko cannot be contacted. That's why I'm bothering you

**Comment by melroy89** [comment]
Yea, so I'm pretty sure the framework is trying to execute a non-existing `namekoentrypoints` to the `UserAgent` object, most likely only during start-up. Which in itself can't hurt, but is mostly annoying I think.

**Comment by melroy89** [comment]
Ow.. you could try to do the following:


```py
from fake_useragent import UserAgent

ua = UserAgent(safe_attrs=('namekoentrypoints',))
```

Does it maybe work?

**Comment by ponponon** [comment]
> ```python
> fake_useragent
> ```

It doesn't work because the program starts with the nameko command, so nameko starts accessing fake useragent after ua = UserAgent(safe attrs=('namekoentrypoints',))

I will explore the underlying reasons when I have time, and I will update you if I have any conclusions

**Comment by melroy89** [comment]
Since the issue is still present, I will reopen it for you. Do you have an update?
