### ISSUE TITLE
Pylance reports no stub files

### ISSUE THREAD

**Issue by sebastian-correa** [fake-useragent/fake-useragent#344]
I have Pylance configured with `"python.analysis.typeCheckingMode": "strict"` and it's complaining that it doesn't find typing stubs:

<img width="593" alt="image" src="https://github.com/user-attachments/assets/acebe547-9a20-46d4-96f9-395d8a3c7d21">

Would you accept a PR adding type-hints to the whole package?

**Comment by melroy89** [comment]
Yes. Sure I'm fine with introducing pyi stub types.

**Comment by sebastian-correa** [comment]
Not mega familiar with the differences between using `.pyi` files and embedding the type-hints directly. Do you have a preference for one or the other? I'd imagine the `.pyi` files are trickier to maintain because, if someone changes the code, they have to remember to go change the `.pyi` files.

From [here](https://github.com/fake-useragent/fake-useragent/blob/6a65e379b37521c62d04ed8b2d1b3c5c8b5dd1be/pyproject.toml#L54C19-L54C23) I'd say typing should support Python 3.7 and up, but the README says `3.x`. Is targeting 3.7+ okay?

Edit: 3.7 is [EOL](https://devguide.python.org/versions/).

**Comment by melroy89** [comment]
Ow that is just Ruff, I will check if I would update this. But it's just a minimal version that Ruff uses: https://docs.astral.sh/ruff/settings/#target-version

Ideally target 3.9 or higher maybe already. I will also check if I need to update any github actions. Both 3.7 and soon 3.8 will be eol. 

Embedded type hints is also fine by me! And you're right, the closer these types are to the code the better it will be for maintainability. Thanks in advance.

**Comment by melroy89** [comment]
**Small update:** I did update GitHub Actions, update the test matrix in GitHub as well as updating the `target-version` to `py39` as well now. See: https://github.com/fake-useragent/fake-useragent/pull/345
