### ISSUE TITLE
Mutable defaults should be replaced with `None`s

### ISSUE THREAD

**Issue by sebastian-correa** [fake-useragent/fake-useragent#353]
Mutable defaults are a bad idea in general. For example, modifications to some instances can affect others:

```python
>>> from fake_useragent import FakeUserAgent
>>> ua1 = FakeUserAgent()
>>> ua1.browsers
['chrome', 'edge', 'firefox', 'safari']
>>> ua1.browsers.append("opera")
>>> ua2 = FakeUserAgent()
>>> ua2.browsers
['chrome', 'edge', 'firefox', 'safari', 'opera']
```

They're in use here:

https://github.com/fake-useragent/fake-useragent/blob/dfb535ac53a264e163d86bbf3493978e23bb2160/src/fake_useragent/fake.py#L9-L22

What do you think if we change those defaults to `None` and, in case we get `None`, we use the current default values?

I can tackle this in a separate PR if you agree!

**Comment by melroy89** [comment]
This is indeed not working as intended. 

I wasn't aware of this.. But when creating a new class I would expect that it will use the defaults as defined above in the `__init__` method. Why would Python reuse data from another object? Wth

**Comment by sebastian-correa** [comment]
Defaults are assigned at class (or method) definition time, and lists are mutable (as opposed to tuples). Because the default is assigned ONCE at definition time, when you mutate some instance's `browser`, you're editing the underlying list.

Some info [here](https://docs.python-guide.org/writing/gotchas/#mutable-default-arguments).

I can submit a PR for this tonight!
