### ISSUE TITLE
Methods should have docstrings

### ISSUE THREAD

**Issue by sebastian-correa** [fake-useragent/fake-useragent#355]
I think methods and instance variables should be documented with docstrings. With this, we could even deploy some pretty docs for free with GitHub pages.

Would you be willing to look into a PR documenting the codebase? I prefer Google Styled docstrings, but I could also submit them in Numpy if you're so inclined.

Ruff has some tools to ensure docstrings remain up-to-date with method signatures, and to ensure their formatting is correct. We could enable those.

**Comment by melroy89** [comment]
I fully agreed!  I refactored this project 3 times now. But I hope we are just using a local json file for now and in the future, without too much changes. Documenting all the methods and variables should help everybody including developers.

**Comment by sebastian-correa** [comment]
On this.
