### ISSUE TITLE
The `U` ruff rule doesn't exist

### ISSUE THREAD

**Issue by sebastian-correa** [fake-useragent/fake-useragent#363]
The `U` rule doesn't exist for `ruff`. Was the idea to turn on `UP`?

https://github.com/fake-useragent/fake-useragent/blob/5de0ce100e9145dcbe18bee0371603e2745c74b6/pyproject.toml#L59

**Comment by melroy89** [comment]
Maybe it's a deprecated option?

**Comment by sebastian-correa** [comment]
I checked in the blame of ruff's TOML spec and in ruff's changelog and it _seems to me_ it was never there.
