### ISSUE TITLE
Urllib timeout

### ISSUE THREAD

**Issue by lockie** [fake-useragent/fake-useragent#39]
Hello!
Thanks for cool library.
I have one issue though: on my hardware I see the exception "Error occurred during formatting data. Trying to use fallback server" too often. Hardcoding `settings.HTTP_TIMEOUT` to large value like 10 makes it go away though. Could you please increase it a bit (say, to 5) or maybe add a possibility to define particular timeout when creating `UserAgent` instance?

**Comment by pcinkh** [comment]
@lockie hey! Thanks! I'll try to investigate and make changes asap!

**Comment by pcinkh** [comment]
@hellysmile I've measured response time from 3 different locations, it's may take up to 5 seconds =(

**Comment by hellysmile** [comment]
Ok, lets set default to 5, and allow to pass it as parameter

**Comment by hellysmile** [comment]
0.1.5 was just released, HTTP_TIMEOUT is 5 seconds
