### ISSUE TITLE
Error occurred during getting browser: shape, but was suppressed with fallback.

### ISSUE THREAD

**Issue by yuanjie-ai** [fake-useragent/fake-useragent#390]
why?
![image](https://github.com/user-attachments/assets/d5df9fdf-1460-4bdb-9e03-dd49702ab55a)

**Comment by melroy89** [comment]
don't try to get a browser name "shape". Valid inputs are firefox or chrome for example.

**Comment by sebastian-correa** [comment]
Hey @yuanjie-ai can you provide an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example.)? On the surface it looked like you're trying to `fake_user_agent["shape"]` and, as @melroy89 said, that isn't a valid browser name.

**Comment by melroy89** [comment]
> On the surface it looked like you're trying to `fake_user_agent["shape"]` and, as @melroy89 said, that isn't a valid browser name.

I also often see framework doing something crazy like this, so the user doesn't know about it. It seems a bit similar to: https://github.com/fake-useragent/fake-useragent/issues/342

**Comment by sebastian-correa** [comment]
I'm closing due to a lack of further info from the reporter. @yuanjie-ai feel free to re-open the issue if you can add the extra info! :)
