### ISSUE TITLE
use_external_data

### ISSUE THREAD

**Issue by Arrowar** [fake-useragent/fake-useragent#399]
Is there a possibility to reintroduce the use_external_data=True parameter for new versions?

**Comment by melroy89** [comment]
No. 😅

**Comment by Arrowar** [comment]
> No. 😅

Thank man, but why ?

**Comment by melroy89** [comment]
See: https://github.com/fake-useragent/fake-useragent/issues/333#issuecomment-2495980155

**Comment by melroy89** [comment]
You can try to latest version now (2.0.0). Update via:

```sh
pip install --upgrade fake-useragent
```
