### ISSUE TITLE
useragentstring.com uptime is low

### ISSUE THREAD

**Issue by hellysmile** [fake-useragent/fake-useragent#4]
list of alternatives
http://user-agent-string.info/list-of-ua

**Comment by ibushong** [comment]
useragentstring.com is down again. Definitely causing me some issues with where I'm using this package.

I think it would a great idea to have a set of fallback agent strings that are embedded with the package. So if the remote service is down, we just return a random string from some pre-set list. This feature could also be enabled/disabled via kwarg.

**Comment by damienkilgannon** [comment]
useragentstring.com is down still ..... my spiders are using 'scrapy-fake-useragent' and are hard failing when the request to useragentstring.com fails. I have removed 'fake-useragent' dependency for them the time been. Any solutions to this problem would be great.

**Comment by ibushong** [comment]
In case it helps anyone, here is a cached backup of data file I had: http://pastebin.com/iqv7nzYA

You can put it in `/tmp/fake_useragent_0.1.2.json` (assuming `tempfile.gettempdir()` points to `/tmp` on your implementation), or use it directly of course.

**Comment by hellysmile** [comment]
As November 24, 2016 library is working again, thanks @pcinkh for https://github.com/hellysmile/fake-useragent/pull/33 . I am looking for new source with useragents

**Comment by hellysmile** [comment]
I think we will give http://www.useragentstring.com/ 1 week to get fixed, otherwise only hosted data will be used for loading data sources, cuz right now libriary takes up to 10 sec to get working on initial launch.

Btw, 0.1.4 with bunch of features(data file location, fallback browser and more) coming soon

**Comment by ibushong** [comment]
It's back! http://www.useragentstring.com/

Now with 0.1.3 we should be good for the future.

**Comment by hellysmile** [comment]
@ibushong awesome news!

**Comment by damienkilgannon** [comment]
in the future should http://www.useragentstring.com/ experience down time again, how will fake-useragent handle it?

**Comment by hellysmile** [comment]
@damienkilgannon, Hey, since version 0.1.3 we have implemented self hosted fallback server, it should working fine

**Comment by damienkilgannon** [comment]
@hellysmile just looking at the code and I see that fallback defaults to none .... could this be changed to a fallback fallback user agent?

**Comment by hellysmile** [comment]
@damienkilgannon , You are looking right now to 0.1.4, which is not released yet.

> to a fallback fallback user agent?

I do not understand it.

Yes, fallback is `None` for now, it fails if now way to crawl websites or download hosted json data(it is really rare case). As for me it is quite normal default behavior.  You can change to any string what You prefer. I do not like to hardcode random one my own, cuz I have no idea which user agent string must be hardcoded.

It can be surprise if `ua.random` returns same every time without configuration.

btw: I think we need to add `logging.warning` in case if fallback is used, as well `logging.error` for services which is down.

**Comment by pcinkh** [comment]
@hellysmile @damienkilgannon logger is ready [here](https://github.com/hellysmile/fake-useragent/pull/36)

**Comment by damienkilgannon** [comment]
@hellysmile yes your dead right, wouldn't make sense to hardcode a fallback useragent and with the fallback hosted data added its likely it will not be required at all. Thanks.

**Comment by hellysmile** [comment]
there will be switch to https://developers.whatismybrowser.com/useragents/explore/ soon
