### ISSUE TITLE
Error occurred during getting browser(s): random, but was suppressed with fallback.

### ISSUE THREAD

**Issue by MisileLab** [fake-useragent/fake-useragent#407]
code
```py
from fake_useragent import UserAgent
print(UserAgent(platforms=['pc'], browsers=['chrome', 'edge']).random)
```
error
```
Error occurred during getting browser(s): random, but was suppressed with fallback.
```

**Comment by melroy89** [comment]
Instead of pc. Could you try desktop as platform?

**Comment by melroy89** [comment]
Also the browser names are now case-sensitive from v2.0 on-wards. So try this instead:

```py
print(UserAgent(platforms=['desktop'], browsers=['Chrome', 'Edge']).random)
```

**Comment by MisileLab** [comment]
thanks, I don't know about that.

**Comment by melroy89** [comment]
See release notes: https://github.com/fake-useragent/fake-useragent/releases/tag/2.0.0

**Comment by siera-papa** [comment]
The error seems to be related to passing less than the default number of os, platforms and/or browsers to UserAgent(). 
My script has been constantly falling back to the default ua since I've implemented a weighted selection of these parameters.
