### ISSUE TITLE
Error occurred during getting browser

### ISSUE THREAD

**Issue by chrisspen** [fake-useragent/fake-useragent#41]
I have a package that depends on fake-useragent, and recently, it's automated unittests have been failing because fake-useragent has been timing out when it tries to retrieve agents.

     File "/home/travis/build/chrisspen/howdou/.tox/py27/lib/python2.7/site-packages/fake_useragent/fake.py", line 98, in __getattr__

        raise FakeUserAgentError('Error occurred during getting browser')  # noqa

What's causing this? Am I hitting some web resource too much, or is it a bug in fake-useragent? What can I do to minimize this or cache the results locally?

**Comment by stamaimer** [comment]
I also met this exception. What's the meaning of `noqa`?

**Comment by pcinkh** [comment]
@chrisspen @stamaimer hey! Currently lib has issue with IE, but it should work over the cache server. Can You specify your current version of lib, You can do that with "import fake_useragent;
print(fake_useragent.VERSION)"
@stamaimer also I can have explanation of noqa for You, this comment makes skip code linter current line which length is over 80 characters while building module in CI. So you shouldn't worry # noqa isn't change behaviour of code.

**Comment by pcinkh** [comment]
@chrisspen @stamaimer I've made fix PR https://github.com/hellysmile/fake-useragent/pull/42
Let's wait for @hellysmile

**Comment by thatguysimon** [comment]
Having the same issue here. Version 0.1.4
Any workarounds until this is fixed?

**Comment by slyapustin** [comment]
The root of the issue is due to having inconsistent browser data for `ie/edge`:
http://useragentstring.com/pages/useragentstring.php?name=ie/edge
So cached file have no data for them:
```json
"ie/edge": []
```
and `random.choice([])` will fail if `ie/edge` selected.

**Comment by hellysmile** [comment]
0.1.5 was just released, issue is solved!

**Comment by metulburr** [comment]
I got this same issue in VERSION = '0.1.7'

**Comment by hellysmile** [comment]
@metulburr are You using scrapy-fake-useragent?

**Comment by metulburr** [comment]
not that i am aware of. I am using...
https://pypi.python.org/pypi/fake-useragent

The full error i get is
```
metulburr@ubuntu:~$ dgsurvey 
Traceback (most recent call last):
  File "/usr/lib/python3.5/random.py", line 253, in choice
    i = self._randbelow(len(seq))
  File "/usr/lib/python3.5/random.py", line 230, in _randbelow
    r = getrandbits(k)          # 0 <= r < 2**k
ValueError: number of bits must be greater than zero

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/fake_useragent/fake.py", line 136, in __getattr__
    return random.choice(self.data_browsers[browser])
  File "/usr/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/dgsurvey", line 140, in <module>
    data = Data(False)
  File "/usr/bin/dgsurvey", line 23, in __init__
    self.setup_driver(self.url)
  File "/usr/bin/dgsurvey", line 48, in setup_driver
    opts.add_argument("user-agent={}".format(self.user_agent.random))
  File "/usr/local/lib/python3.5/dist-packages/fake_useragent/fake.py", line 139, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
fake_useragent.errors.FakeUserAgentError: Error occurred during getting browser
```

Where i am using it within selenium
```from selenium.webdriver.chrome.options import Options
from fake_useragent import UserAgent
...
        self.user_agent = UserAgent()
...
        opts = Options()
        opts.add_argument("user-agent={}".format(self.user_agent.random))
```

**Comment by metulburr** [comment]
I used this to get the program to work 
```
        self.user_agent = UserAgent(fallback='Mozilla/5.0 (compatible; Googlebot/2.1; ')
```
if in the event the fake useragent works or doesnt work. But i havent been able to get it to work at all today.

**Comment by atmatul** [comment]
I am getting the same issue with creating a fake_useragent object. 

`from fake_useragent import UserAgent`
`ua = UserAgent()`

Results in :

Traceback (most recent call last):
  File "filepath\lib\site-packages\fake_useragent\fake.py", line 136, in __getattr__
    return random.choice(self.data_browsers[browser])
KeyError: 'len'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "filepath\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.6494.30\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 274, in frame_vars_to_struct
    value = var_to_struct(v, str(k), evaluate_full_value=eval_full_val)
  File "filepath\AppData\Local\JetBrains\Toolbox\apps\PyCharm-P\ch-0\193.6494.30\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_thrift.py", line 358, in var_to_struct
    elif hasattr(v, '__len__') and not is_string(v):
  File "filepath\lib\site-packages\fake_useragent\fake.py", line 139, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
fake_useragent.errors.FakeUserAgentError: Error occurred during getting browser
Unexpected error, recovered safely.


I am using Python 3.7.
