### ISSUE TITLE
os param consistency

### ISSUE THREAD

**Issue by matecsaj** [fake-useragent/fake-useragent#414]
For consistency, please use the same operating system names as Python's library:

https://docs.python.org/3/library/platform.html#platform.system

platform.system()
Returns the system/OS name, such as 'Linux', 'Darwin', 'Java', 'Windows'. An empty string is returned if the value cannot be determined.

On iOS and Android, this returns the user-facing OS name (i.e, 'iOS, 'iPadOS' or 'Android'). To obtain the kernel name ('Darwin' or 'Linux'), use [os.uname()](https://docs.python.org/3/library/os.html#os.uname).

Now.
```
os = platform.system()
if os == "Darwin":
    os = "Mac OS X"
# TODO check if other operating system names need substitution
ua = UserAgent(os=os)
```
        
Future.
```
ua = UserAgent(os=platform.system())
```

Smooth transition.

To avoid breaking end-user code, introduce a two-year transition period. During this time, implement logic like the following in the fake-useragent codebase. Consider applying similar changes for other parameters that were recently renamed in version 2 of fake-useragent.
```
import warnings

if os == "Darwin":
    warnings.warn(
        "'Mac OS X' is deprecated, use 'Darwin' instead for compatibility with Python's platform module.",
        DeprecationWarning,
        stacklevel=2
    )
    os = "Mac OS X"
```

**Comment by melroy89** [comment]
We use the data from Intoli. We just use the data as-is. You might want to create a ticket about this at: https://github.com/intoli/user-agents/issues instead

**Comment by matecsaj** [comment]
Thanks for explaining why your library uses "Mac OS X." It seems the Intoli project works within the JavaScript ecosystem. I don’t program in JavaScript, but based on the following ChatGPT code, "Mac OS X" appears to be the proper name:

```
function getOperatingSystem() {
    const userAgent = navigator.userAgent || navigator.vendor || window.opera;

    if (/Windows NT 10\.0/.test(userAgent)) return "Windows 10";
    if (/Windows NT 6\.3/.test(userAgent)) return "Windows 8.1";
    if (/Windows NT 6\.2/.test(userAgent)) return "Windows 8";
    if (/Windows NT 6\.1/.test(userAgent)) return "Windows 7";
    if (/Windows NT 6\.0/.test(userAgent)) return "Windows Vista";
    if (/Windows NT 5\.1/.test(userAgent)) return "Windows XP";
    if (/Macintosh|Mac OS X/.test(userAgent)) return "MacOS";
    if (/Linux/.test(userAgent)) return "Linux";
    if (/Android/.test(userAgent)) return "Android";
    if (/iPhone|iPad|iPod/.test(userAgent)) return "iOS";

    return "Unknown OS";
}

// Example usage:
console.log("Current Operating System:", getOperatingSystem());
``` 

A possible compromise might be for your library to accept both "Darwin" and "Mac OS X," automatically converting the first to the second. Another option is to include a note in the README file, warning users about the intentional inconsistency.

That said, your library works great as it is, so no changes are strictly necessary. I defer to your judgment on how "Pythonic" you want your library to be.

Thanks for providing this great tool to the world.

**Comment by melroy89** [comment]
We just use the data file at: https://github.com/intoli/user-agents/blob/main/src/user-agents.json.gz

**Comment by melroy89** [comment]
Ow the `os` we get from another Python pip package called: `ua_parser`: https://github.com/ua-parser/uap-python

Which we use here: https://github.com/fake-useragent/fake-useragent/blob/main/ua-converter/ua_convert.py#L78C15-L78C24

**Comment by sebastian-correa** [comment]
Hi @matecsaj, thanks for the report. As @melroy89 said, we're using Intoli's data directly. Notwithstanding, you bring up a good point with a use case I can see as widely used.

I'm not familiar with the output of those `os` functions you mentioned. I'll have to look at this. We can implement a translation layer to fix this, probably. I'd be thankful if you could provide some pointers (aside from Python docs) to find all possible output of those functions.

I don't see us implementing the transition period for other attributes, though. We released a v2, and users should check compatibility when upgrading. The changes aren't substantial enough that most users will have a hard time adjusting, I think. We could consider this in the future though, there's no such policy in place now so we didn't even consider it.

**Comment by matecsaj** [comment]
Hey @sebastian-correa. Windows and Linux work fine as is. Darwin is troublesome. I don't have experience with other platforms.

**Comment by sebastian-correa** [comment]
I looked into this superficially and it seems each OS can respond whatever they want, so we should probably start with a base translator for all OSs that we currently know of and add others as they appear.

We can add a workflow checking for unknown OSs to PRs that update the UAs file.

I can look into this (probably by the end of next week) if we deem this a good idea. I vote 👍, not sure what @melroy89 thinks.

**Comment by melroy89** [comment]
I personally do not want to make this specific package unnecessary complex. If you do not agree with the OS output, you can complain to them: https://github.com/ua-parser/uap-python
