### ISSUE TITLE
Update `README.md` to show correct information regarding the new automation script

### ISSUE THREAD

**Issue by SamuMazzi** [fake-useragent/fake-useragent#421]
> We are currently working on a new automation script (see issue #333) to fetch user-agent scripts from user-agents.net and up date the user-agents once in a while.

I'm new to this library but I've seen this line and I noticed that this issue has been recently closed so maybe this line should be changed too.

Anyway thanks for the great job you're doing ;)

**Comment by melroy89** [comment]
Yea I think so yes haha.

**Comment by melroy89** [comment]
Sentence removed.
