### ISSUE TITLE
FakeUserAgentError on concurrent requests on Linux Server

### ISSUE THREAD

**Issue by vionemc** [fake-useragent/fake-useragent#49]
```
Traceback (most recent call last):
  File "/usr/local/lib64/python2.7/site-packages/twisted/internet/defer.py", line 1299, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/usr/local/lib/python2.7/site-packages/scrapy_fake_useragent/middleware.py", line 27, in process_request
    request.headers.setdefault('User-Agent', self.ua.random)
  File "/usr/local/lib/python2.7/site-packages/fake_useragent/fake.py", line 98, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
FakeUserAgentError: Error occurred during getting browser
```

I keep getting this error on the Linux server when I run multiple spiders concurrently. What should I do to avoid that? Do I have to raise the RAM or something?

**Comment by pcinkh** [comment]
Sry for long answer @vionemc 
To make issue more clearly please specify your Fake UserAgent version that currently is using. You can do that with python "import fake_useragent;
print(fake_useragent.VERSION)" with environment of your project.
I have some ideas, but first of all let's clarify module version.

**Comment by vionemc** [comment]
I am glad you are replying!
It's version 0.1.4.
Thanks!

**Comment by pcinkh** [comment]
@vionemc immediately update your version to the latest, it's 0.1.5. You can do this with "pip install -U fake-useragent"
Please, don't forget to notify us here if this helped you or not in both cases.
Also, recommend you to "Star" library on github to be up-to-date with any news, releases, etc.

**Comment by vionemc** [comment]
Yup, that solves the problem. Thanks! Still curious though why it only happens on the server but not on my machine. 

I am considering raising the RAM

**Comment by pcinkh** [comment]
@vionemc ok, nice! Anyway I very much doubt that you need to raise RAM.

**Comment by vionemc** [comment]
Great! Thx!
