### ISSUE TITLE
Create some tag releases

### ISSUE THREAD

**Issue by likewhoa** [fake-useragent/fake-useragent#50]
Not everyone uses pip and in order to fetch the project besides pulling from master, it would be ideal to fetch from tags from a package manager perspective that is. Thanks in advanced

**Comment by hellysmile** [comment]
https://github.com/hellysmile/fake-useragent/releases

I see, there always be a tag for next releases, as well current pypi version is tagged

**Comment by likewhoa** [comment]
Thank you!
