### ISSUE TITLE
Error occurred during fetching https://www.w3schools.com/browsers/default.asp

### ISSUE THREAD

**Issue by fifyrio** [fake-useragent/fake-useragent#51]
Hi,buddy,I found a bug like this:
DEBUG: Error occurred during fetching https://www.w3schools.com/browsers/default.asp
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fake_useragent/utils.py", line 67, in get
    context=context,
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1258, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
Hope to be solved,thank you

**Comment by pcinkh** [comment]
Hi, @fifyrio will glad to help you!

To make the issue more clearly please specify your Fake UserAgent version that currently is using. You can do that with python "import fake_useragent;
print(fake_useragent.VERSION)" with the environment of your project.
I have some ideas, but first of all, let's clarify module version.

**Comment by zephoon** [comment]
Hi.I have the same issue.
My fake_useragent's version is 1.7.0.

**Comment by hellysmile** [comment]
Can You open in Your browser https://www.w3schools.com/browsers/default.asp ?

**Comment by pcinkh** [comment]
@hellysmile also checking it now...

**Comment by pcinkh** [comment]
@zeffon just checked it works fine for me, also update please to 1.8.0 and try to follow @hellysmile advice try to https://www.w3schools.com/browsers/default.asp in the browser just to be sure that resource is available from your location.

**Comment by hellysmile** [comment]
@pcinkh there is no 0.1.8 yet, as well no changes

**Comment by zephoon** [comment]
Sometime I can open in my browser，but nothing change.

**Comment by hellysmile** [comment]
Are You using scrapy-fake-user agent?

**Comment by fifyrio** [comment]
yes

**Comment by hellysmile** [comment]
It is scrapy-fake-useragent issue regarding mobile/desktop and should for first be fixed there
