### ISSUE TITLE
FakeUserAgentError('Error occurred during getting browser')

### ISSUE THREAD

**Issue by mikkokotila** [fake-useragent/fake-useragent#52]
I'm getting this error with version 0.1.7 running on Mac OS X. It seems that the common suggestion to this is to update the version, but I think I have a version where this error should not come anymore? Any ideas? 

`Traceback (most recent call last):
  File "/Users/mikko/dev/norway/lib/python2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/Users/mikko/dev/norway/lib/python2.7/site-packages/scrapy/core/downloader/middleware.py", line 37, in process_request
    response = yield method(request=request, spider=spider)
  File "/Users/mikko/dev/norway/lib/python2.7/site-packages/scrapy_fake_useragent/middleware.py", line 28, in process_request
    self.proxy2ua[proxy] = get_ua()
  File "/Users/mikko/dev/norway/lib/python2.7/site-packages/scrapy_fake_useragent/middleware.py", line 23, in get_ua
    return getattr(self.ua, self.ua_type)
  File "/Users/mikko/dev/norway/lib/python2.7/site-packages/fake_useragent/fake.py", line 139, in __getattr__
    raise FakeUserAgentError('Error occurred during getting browser')  # noqa
FakeUserAgentError: Error occurred during getting browser`

**Comment by hellysmile** [comment]
Looks like duplicat of https://github.com/hellysmile/fake-useragent/issues/51

I really can  ot reproduce it...  where You from? Maybe some firewall issues?

**Comment by mikkokotila** [comment]
Thanks for super quick response! :) I tried installing 1.8 from git just now, but also same problem. I'm in Estonia, I don't think I have any firewall issue. Can you give some background to the process this is happening as part of, maybe I will look in to it and see if there is a work around.

**Comment by mikkokotila** [comment]
Not sure if this is generic, but I think this have to do with the settings.py. Once I turn off all the proxy related configs, I get past the error. So maybe a user / configuration issue, with ambiguous error message? Does that make sense?

**Comment by hellysmile** [comment]
How do You set/turn off proxy configs?

**Comment by mikkokotila** [comment]
At the end of settings.py (the package I'm working with had some proxy related configurations enabled). But I have to warn you, I'm totally new to this, it's the first time I'm using a scraping library of any sort as I've always done everything with custom scripts so I'm still pretty confused.

**Comment by hellysmile** [comment]
Can You try to execute samples from main page of this package?

**Comment by mikkokotila** [comment]
Yes this is working. Can you explain where this is called, for example the fallback, where would that be in the code? The codes that I'm running do not reference this package anywhere? Is it called inside scrapy and then activated through the settings?

**Comment by mikkokotila** [comment]
ok I think I got it > RANDOM_UA_TYPE = 'desktop' in settings.py

If I turn that on, then I get the error, when I turn it off, I don't.

**Comment by hellysmile** [comment]
It seems You are using https://github.com/alecxe/scrapy-fake-useragent

If examples works for You, and scrapy-fake-useragent no, that’s might be an issue there

**Comment by hellysmile** [comment]
According to what I see there some issues in docs of scrapy-fake-useragent , mobile/desktop types is not supported yet.

**Comment by mikkokotila** [comment]
Thanks Dude, the most responsive repo owner ever! :) 

Ok I understand now, also that helped me to set the FAKEUSERAGENT_FALLBACK = 'Mozilla' which seems to be the key to resolving this issue. 

Also now my package work, and I'm getting data in :) 

Thanks again and have a great weekend ahead as well.

**Comment by hellysmile** [comment]
You are welcome

**Comment by Luxrare-io** [comment]
> Thanks Dude, the most responsive repo owner ever! :)
> 
> Ok I understand now, also that helped me to set the FAKEUSERAGENT_FALLBACK = 'Mozilla' which seems to be the key to resolving this issue.
> 
> Also now my package work, and I'm getting data in :)
> 
> Thanks again and have a great weekend ahead as well.

Hi, where is file for edit this line?
