### ISSUE TITLE
useragentstring.com (and as a result fake-useragent) is Out of Date

### ISSUE THREAD

**Issue by speedplane** [fake-useragent/fake-useragent#54]
The service this library relies on to get user agent data is woefully out of date.

This library pulls from [this page to get firefox](http://useragentstring.com/pages/useragentstring.php?name=firefox) User Agent strings, but it looks like it only goes up to version 40.1, which was released in 2015.

Similarly, [chrome versions are pulled](http://useragentstring.com/pages/useragentstring.php?name=chrome) from here and only go up to version 41.

**Comment by hellysmile** [comment]
Hey @speedplane , I agree that is some kind of issue.
If You can help us to find better sources I'll implement them

**Comment by metulburr** [comment]
This has some of the latest
https://techblog.willshouse.com/2012/01/03/most-common-user-agents/

and here
https://developers.whatismybrowser.com/useragents/explore/

**Comment by hellysmile** [comment]
@metulburr  https://developers.whatismybrowser.com/useragents/explore/ is perfect! new release will be in a week+-

**Comment by hellysmile** [comment]
Sorry for release delay we got some misunderstood with committers, there will be minor quickfix release on next Moday , due https://github.com/hellysmile/fake-useragent/issues/62

**Comment by melroy89** [comment]
Yea we might need to change source to a newer user-agent list.

See dup: https://github.com/fake-useragent/fake-useragent/issues/109

**Comment by melroy89** [comment]
Dammit. https://techblog.willshouse.com/ is now down... ;( Which was our main source.
