### ISSUE TITLE
Distinguish between desktop and mobile (Android vs iOS)

### ISSUE THREAD

**Issue by acefei** [fake-useragent/fake-useragent#61]
I writes a spider to crawl the web from PC front with `ua.random`, but sometimes, it would redirect to mobile front , that's not what I expected.
I found it caused by `ua.random` would return a mobile ua as below:
```
import requests
res = requests.get("https://fake-useragent.herokuapp.com/browsers/0.1.5")
print res.json()['browsers']['safari'][41]
# Mozilla/5.0 (Android 2.2; Windows; U; Windows NT 6.1; en-US) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4
```
From https://github.com/hellysmile/fake-useragent/issues/10#issuecomment-341654267, there will be eventually added `ua.desktop` and `ua.mobile`, I'm really looking forward to it.

**Comment by james-see** [comment]
@acefei I second this idea. Would be great to randomly select between desktop or just mobile depending on the implementation.

**Comment by bernardosrulzon** [comment]
+1! 👍

**Comment by iAnanich** [comment]
Just tested - it's pretty easy to know if user-agent is meant to be mobile - just check for `mobile` in lowercase user-agent string.

**Comment by MAH69IK** [comment]
Hi friends!
Try my changes - https://github.com/hellysmile/fake-useragent/pull/105
With it you can use `ua.mobile` and `ua.desktop`.

**Comment by Louvivien** [comment]
+1

**Comment by melroy89** [comment]
The data we now use doesn't contain mobile (eg. Android) user agent strings: https://github.com/fake-useragent/fake-useragent/blob/master/src/fake_useragent/data/browsers.json

**Comment by roke-julian-lockhart** [comment]
> ~~https://github.com/fake-useragent/fake-useragent/issues/61#issuecomment-1651528207~~

@melroy89, why is that better than distinguishing between them?

**Comment by melroy89** [comment]
We just don't have mobile user strings from the new data source.
