### ISSUE TITLE
Maximum amount of retries reached

### ISSUE THREAD

**Issue by ShengM97** [fake-useragent/fake-useragent#63]
I can not access "www.w3schools.com" in China,so I can't call get_browsers() in utils.py.

**Comment by hellysmile** [comment]
Can You open https://fake-useragent.herokuapp.com/browsers/0.1.5 in China?

**Comment by ShengM97** [comment]
@hellysmile yes i can.Just can't access w3schools.com,but I can access w3schools.com.cn in China

**Comment by hellysmile** [comment]
Next major release will use aws cloudfront for serving data, it should fix this issue. Ill post update here soon

**Comment by hellysmile** [comment]
0.1.9 with cloudfront was released, please open new issue if it fails again for You
