### ISSUE TITLE
Certain sites will not be accessible with out of date random user agents.

### ISSUE THREAD

**Issue by wolfamongus2** [fake-useragent/fake-useragent#66]
For me, certain sites will not be accessible with out of date random user agents using this library.

This might just be a limitation of this library, but I thought I would add my 2c in saying that adding an option for most popular user strings to prevent unable to access might be worthwhile.  

E.g Taken From here-
https://developers.whatismybrowser.com/useragents/explore/software_name/chrome/

Might be of use.  I use Chrome a lot so hence this example.

**Comment by james-see** [comment]
Do sites really block user agents that are too old?

**Comment by symbiotech** [comment]
@jamesacampbell They don't actually block users, but they redirect them to a page recommending to upgrade the browser. Here's an example encountered recently:

http://www.keurig.com/upgrade-browser-us.html

**Comment by james-see** [comment]
@symbiotech ok that makes sense.

**Comment by samshipengs** [comment]
@wolfamongus2 did you end up finding a solution for this?

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/109
