### ISSUE TITLE
Один и тот же useragent

### ISSUE THREAD

**Issue by Rashefort** [fake-useragent/fake-useragent#67]
Добрый день. Хотелось бы видеть в новой версии возможность получения одного и того же useragent. К примеру, ua = UserAgent(last=True), после чего ua.chrome ВСЕГДА выдаёт самый свежий (для данной базы) useragent для этого браузера.

Для чего это надо - я ежедневно захожу на сайт, который при авторизации запрашивает и userkey, который высчитывается в том числе и на основе строки useragent. Если я буду ежедневно (по несколько раз) заходить с разным userkey, то это неизбежно вызовет подозрения.

ps: "ВСЕГДА" - в смысле не только для одной сессии, а при любом запуске скрипта.

**Comment by slyapustin** [comment]
Why can't you just store your generated `ua`on your side?

**Comment by Rashefort** [comment]
Это такой тонкий английский юмор? Или же вы предлагаете мне получить useragent от fake-useragent, сохранить его на диске, при следующем запуске скрипта проверить существует ли файл с юзерагентом, и если существует, то прочитать строку из файла? Сергей, я вам подскажу вариант попроще - прописать строку useragent'а сразу в скрипте. Я согласен, такой вариант оригинальностью не дышит, но поверьте мне на слово, так будет проще. Даю вам честное и благородное слово. Попробуйте, вам понравится.

**Comment by slyapustin** [comment]
>>"ВСЕГДА" - в смысле не только для одной сессии, а при любом запуске скрипта.

>Или же вы предлагаете мне получить useragent от fake-useragent, сохранить его на диске, при следующем запуске скрипта проверить существует ли файл с юзерагентом, и если существует, то прочитать строку из файла

Именно так.

**Comment by Rashefort** [comment]
Нет, я категорически отказываюсь так делать, на меня друзья станут подозрительно смотреть. Нафиг мне такие стрессы? Я уже списывался с Виктором и он меня заверил, что функционал подобный моей просьбе можно без проблем ввести в новой версии. Если вы не возражаете, то я, как только она появится, буду пользоваться именно ей. И если вам будет легче, то можете на меня подозрительно смотреть, я не обижусь.
