### ISSUE TITLE
ua.chrome need upgrade

### ISSUE THREAD

**Issue by incipient1** [fake-useragent/fake-useragent#68]
`fake-useragent.UserAgent().chrome`
return 
'Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.93 Safari/537.36'
but the newest chrome is 
'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36'
Chrome/27.0 is too old, and when I request 'https://www.zhihu.com/sigup', I'm redirected to 'https://www.zhihu.com/compatibility/index.html'

**Comment by acgxv** [comment]
I got the same problem.

Some website will check if your browser version to fit their js or css.

**Comment by melroy89** [comment]
Yea we might need to change source to a newer user-agent list.

See dup: https://github.com/fake-useragent/fake-useragent/issues/109
