### ISSUE TITLE
Need disable/enable mobile browser agents.

### ISSUE THREAD

**Issue by smallcrocodile** [fake-useragent/fake-useragent#70]
This is just a requirement.

In case the spider randomly picks up a mobile browser agent, some PC websites redirect to their mobile sites, this caused a lot of trouble, the scrapy parse method have to handle this extra situation. 
Here is a real case provide for testing, accessing www.shixiseng.com with an Andriod sort browser agent , website redirect to wap.shixiseng.com automatically. 

In contrary, crawl for a mobile site might be redirected to PC website.

So is it possible to have an option, to set use only PC or Mobile browser agent?

Thank You!

Kevin
2018-3-23

**Comment by baby5** [comment]
**UPDATE**: just delete user-agent which has "Mobile"  will work

Use "Windows NT" system only may help you, you need change data file to delete other systems' user-agent and specify the file by `ua = fake_useragent.UserAgent(path=your_data_file_path)`

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/61

**Comment by melroy89** [comment]
Fixed by: https://github.com/fake-useragent/fake-useragent/pull/290
