### ISSUE TITLE
Could we use another source of UA list?

### ISSUE THREAD

**Issue by pomoke** [fake-useragent/fake-useragent#74]
There are not any UAs of new versions of browsers.

**Comment by jboucan** [comment]
[useragentstring.com](useragentstring.com) is clearly not updated anymore. Hard to find an updated list though...

**Comment by pradyunsg** [comment]
Seems like they added newer versions recently.

**Comment by adrianmeraz** [comment]
I really hope a new source is used. Having chrome < v30 is pretty terrible imo

**Comment by pomoke** [comment]
Why not generate UAs?

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/109
