### ISSUE TITLE
Remote cache server is unstable

### ISSUE THREAD

**Issue by Xarrow** [fake-useragent/fake-useragent#77]
In version "0.1.10" , remote cache server is "https://d2g6u4gh6d9rq0.cloudfront.net" , and  now it not work .
In version "0.1.11", remote cache server is "https://fake-useragent.herokuapp.com" , and i worry about that it can not be stable all the time . 

I am stuck on this issue because some project dependent on “fake-useragent”.

**Comment by legut2** [comment]
I've come across this problem too. I would very much like to host my own [cache server](https://github.com/hellysmile/fake-useragent-cache-server). Any advice/resources would be much appreciated. @hellysmile

**Comment by melroy89** [comment]
Solved.
