### ISSUE TITLE
It would be cool to have a possibility for adding the proxies.

### ISSUE THREAD

**Issue by perfectuser12** [fake-useragent/fake-useragent#79]
There is a case that I use this awesome package on the machine with requests only through some proxies. 
For example the proxy might be {'https': 'http://user:pass@proxy:123'} or {'http': 'http://user:pass@proxy:123'} or even {'socks5': 'http://user:pass@proxy:123'}.
Today I need to make some tricks to make my requests and for keeping this library working. May be you will have some time for example to create ProxyHandler or something like that.

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/16
