### ISSUE TITLE
Configurable settings

### ISSUE THREAD

**Issue by chripede** [fake-useragent/fake-useragent#8]
I'd like to be able to change settings like BROWSERS_COUNT_LIMIT.
Maybe just as a parameter to the update method.

**Comment by hellysmile** [comment]
Feel to free to make pull request...

**Comment by hellysmile** [comment]
Bit tricky, but I don't want to make settings configurable, at least I can not see any reason for this...

``` python
from fake_useragent import settings


settings.BROWSERS_COUNT_LIMIT = 42

from fake_useragent import UserAgent
```
