### ISSUE TITLE
Python 3.7 maximum amount of retries reached

### ISSUE THREAD

**Issue by jihwan1008** [fake-useragent/fake-useragent#81]
Hello,

I'd made an image download crawler few months ago, which worked very well.
But when I try to execute my python file it shows up an error message as follows:
**'fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached'**

Any help would be extremely appreciated. Thanks!

**Comment by pol9111** [comment]
same problem

**Comment by Jason-Liu-Dream** [comment]
same problem

**Comment by likenji** [comment]
same problem

**Comment by ghost** [comment]
I got the same problem

**Comment by 111qqz** [comment]
same problem

**Comment by koeniig2** [comment]
Same

**Comment by EdEngle** [comment]
I know this doesn't fix the issue...  but it will get fake-useragent to work.  When initializing the UserAgent module use this.
`ua = UserAgent(verify_ssl=False)`

**Comment by bennypeng** [comment]
ua_file = os.getcwd() + '/commons/fake_useragent.json'
ua = UserAgent(path=ua_file, verify_ssl=False, use_cache_server=False, cache=False)

python3.7 not work....help me

**Comment by kelvin-tran** [comment]
This seems to have been fixed in v0.1.11 (https://github.com/hellysmile/fake-useragent/commit/9fb2ecb4549da10a963686ab97311a357b6e3f1c). The commit redirected the failing request from cloudfront server to heroku (and now no longer fails).

So upgrade to latest version (if you were on < v0.1.11).

**Comment by Freakwill** [comment]
> This seems to have been fixed in v0.1.11 ([9fb2ecb](https://github.com/hellysmile/fake-useragent/commit/9fb2ecb4549da10a963686ab97311a357b6e3f1c)). The commit redirected the failing request from cloudfront server to heroku (and now no longer fails).
> 
> So upgrade to latest version (if you were on < v0.1.11).

I use the latest version, fake-useragent  0.1.11, but have the same problem. I follow EdEngle's method temporarily.

**Comment by Voccoo** [comment]
same problem
python: 3.5
fake-useragent : 0.1.11
use_cache_server=False,cache=False,verify_ssl=False
All three methods have been tried, but they are useless.

Who has a solution?
thanks!

**Comment by eatomelette** [comment]
same problem

**Comment by t-dawei** [comment]
use_cache_server=False,cache=False,verify_ssl=False
no work
Python 3.7

**Comment by wushenchao** [comment]
same problem

**Comment by viponedream** [comment]
just use this
ua = UserAgent(use_cache_server=False)
work fine for me

**Comment by xuyiwg** [comment]
> just use this
> ua = UserAgent(use_cache_server=False)
> work fine for me

thanks

**Comment by jayvdb** [comment]
Full backtrace of the current problem
```py
Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "C:\Python36-x64\lib\urllib\request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Python36-x64\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Python36-x64\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Python36-x64\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Python36-x64\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Python36-x64\lib\http\client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python36-x64\lib\socket.py", line 724, in create_connection
    raise err
  File "C:\Python36-x64\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\projects\pypidb\.tox\py36\lib\site-packages\fake_useragent\utils.py", line 67, in get
    context=context,
  File "C:\Python36-x64\lib\urllib\request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python36-x64\lib\urllib\request.py", line 526, in open
    response = self._open(req, data)
  File "C:\Python36-x64\lib\urllib\request.py", line 544, in _open
    '_open', req)
  File "C:\Python36-x64\lib\urllib\request.py", line 504, in _call_chain
    result = func(*args)
  File "C:\Python36-x64\lib\urllib\request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "C:\Python36-x64\lib\urllib\request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "c:\projects\pypidb\.tox\py36\lib\site-packages\fake_useragent\utils.py", line 166, in load
    verify_ssl=verify_ssl,
  File "c:\projects\pypidb\.tox\py36\lib\site-packages\fake_useragent\utils.py", line 122, in get_browser_versions
    verify_ssl=verify_ssl,
  File "c:\projects\pypidb\.tox\py36\lib\site-packages\fake_useragent\utils.py", line 84, in get
    raise FakeUserAgentError('Maximum amount of retries reached')
fake_useragent.errors.FakeUserAgentError: Maximum amount of retries reached
```

**Comment by Mte90** [comment]
Same error also for me and disable cache server didn't fixed.

**Comment by arubiales** [comment]
Same error! the solutions don't work for me!

**Comment by manikandaprabhuit** [comment]
Same error for me too and disabling cache server did not fix the problem. I use fake_useragent-0.1.11

**Try 1:**

{
  "errorMessage": "Maximum amount of retries reached",
  "errorType": "FakeUserAgentError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 19, in handler\n    chrome_options.add_argument('user-agent='+UserAgent(**use_cache_server=False**).random)\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 69, in __init__\n    self.load()\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 78, in load\n    verify_ssl=self.verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 250, in load_cached\n    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 245, in update\n    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 178, in load\n    raise exc\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 166, in load\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 122, in get_browser_versions\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 84, in get\n    raise FakeUserAgentError('Maximum amount of retries reached')\n"
  ]
}

**Try 2:**

{
  "errorMessage": "Maximum amount of retries reached",
  "errorType": "FakeUserAgentError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 19, in handler\n    chrome_options.add_argument('user-agent='+UserAgent(**use_cache_server=False,verify_ssl=False**).random)\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 69, in __init__\n    self.load()\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 78, in load\n    verify_ssl=self.verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 250, in load_cached\n    update(path, use_cache_server=use_cache_server, verify_ssl=verify_ssl)\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 245, in update\n    write(path, load(use_cache_server=use_cache_server, verify_ssl=verify_ssl))\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 178, in load\n    raise exc\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 166, in load\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 122, in get_browser_versions\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 84, in get\n    raise FakeUserAgentError('Maximum amount of retries reached')\n"
  ]
}

**Try 3:**

{
  "errorMessage": "Maximum amount of retries reached",
  "errorType": "FakeUserAgentError",
  "stackTrace": [
    "  File \"/var/task/index.py\", line 19, in handler\n    chrome_options.add_argument('user-agent='+UserAgent(**cache=False,use_cache_server=False,verify_ssl=False**).random)\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 69, in __init__\n    self.load()\n",
    "  File \"/var/task/fake_useragent/fake.py\", line 83, in load\n    verify_ssl=self.verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 178, in load\n    raise exc\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 166, in load\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 122, in get_browser_versions\n    verify_ssl=verify_ssl,\n",
    "  File \"/var/task/fake_useragent/utils.py\", line 84, in get\n    raise FakeUserAgentError('Maximum amount of retries reached')\n"
  ]
}

**Comment by Amundeep-Dhaliwal** [comment]
I use this code within a docker container. I also encounter this issue, however when I use this:
```
from fake_useragent import UserAgent
UserAgent().random 
```
I am presented with the FakeUserAgentError and the output from my program.
When I use this:
```
UserAgent(use_cache_server=False).random
```
I am only presented with the FakeUserAgentError.
When I run the script outside a docker container I do not get any exceptions.

**Comment by zxdawn** [comment]
This works for me: download the json file manually and copy it to the temp dir:

```
wget https://fake-useragent.herokuapp.com/browsers/0.1.11
mv 0.1.11 fake_useragent_0.1.11.json
cp fake_useragent_0.1.11.json /tmp
```

**Comment by pouria-ariafar** [comment]
No solution found?

**Comment by likenji** [comment]
邮件已到账。我会尽快回复的

**Comment by melroy89** [comment]
Should be fixed by now. Upgrade to the latest release. Thanks.

```sh
pip install --upgrade fake-useragent
```

**Comment by jun3599** [comment]
use other lib for random useragent! 
https://pypi.org/project/latest-user-agents/

it give same utils!

**Comment by likenji** [comment]
邮件已到账。我会尽快回复的
