### ISSUE TITLE
Can I specify a platform when using ua.random?

### ISSUE THREAD

**Issue by ghost** [fake-useragent/fake-useragent#83]
Can I specify a platform when using ua.random?

**Comment by melroy89** [comment]
Like the OS you mean? WIndows, Linux, ..? 

Related: https://github.com/fake-useragent/fake-useragent/issues/96

**Comment by melroy89** [comment]
You can now actually use `browsers=[...]`  parameter on the `UserAgent()` constructor to select which browsers you want to load. `ua.random` will then also only select a random browser from those selected browsers.

More info see the [readme](https://github.com/fake-useragent/fake-useragent).
