### ISSUE TITLE
Good Job, please add ua.mobile or ua.android as option

### ISSUE THREAD

**Issue by xifarm** [fake-useragent/fake-useragent#84]
the source is Good job.

i test in my Mac very usefully.

so , i want to use such command:

```
ua.android 

Mozilla/5.0 (Linux; Android 4.0.4; Galaxy Nexus Build/IMM76B) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.133 Mobile Safari/535.19
```

**Comment by fitoe** [comment]
+1

**Comment by fitoe** [comment]
+1

**Comment by FirstJavaMaster** [comment]
+1

**Comment by One2r** [comment]
+1

**Comment by webruslanmir** [comment]
++++ 
I agree, this is a very necessary option, it would be better if use ua.mobile to use different options for ua.mobile.random

**Comment by anylayer** [comment]
+1

**Comment by tommyct614** [comment]
Hi, any update on this? Does anyone know if ua.mobile is available now? Wasn't able to find anything...

**Comment by Christoph1987** [comment]
+1

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/61

**Comment by melroy89** [comment]
Fixed by: https://github.com/fake-useragent/fake-useragent/pull/290

**Comment by melroy89** [comment]
You can try to latest version now (2.0.0). Update via:

```sh
pip install --upgrade fake-useragent
```
