### ISSUE TITLE
iPhone / iOS User-Agent

### ISSUE THREAD

**Issue by vgoklani** [fake-useragent/fake-useragent#87]
How do I get the iPhone / iOS user-agent? Thanks!

**Comment by tommyct614** [comment]
Don't think this is possible yet... There is one other request for creating ua.mobile user agents

**Comment by Christoph1987** [comment]
I would also like to have an option to only get mobile UAs.

**Comment by melroy89** [comment]
Duplicate: https://github.com/fake-useragent/fake-useragent/issues/61
