### ISSUE TITLE
ValueError: could not convert string to float: <a

### ISSUE THREAD

**Issue by ImanYZ** [fake-useragent/fake-useragent#9]
Here is the whole traceback:

Traceback (most recent call last):
  File "...\fake_useragent\fake.py", line 11, in **init**
    self.data = load_cached()
  File "...\fake_useragent\utils.py", line 133, in load_cached
    update()
  File "...\fake_useragent\utils.py", line 128, in update
    write(load())
  File "...\fake_useragent\utils.py", line 87, in load
    for counter in range(int(float(percent))):
ValueError: could not convert string to float: <a

I tried to upgrade fake-useragent. It did not help.
I also tried pip uninstall fake-useragent and pip install fake-useragent again. It returns the same error message.

By the way, my OS is Windows 8.1.

I'll appreciate it if you help me with this issue.

**Comment by hellysmile** [comment]
can You try

``` Python
from fake_useragent.settings import DB
print(DB)
```

And to remove this file?

**Comment by ImanYZ** [comment]
Here is the result:

c:\users\iman\appdata\local\temp\fake_useragent.json

Should I remove it?

**Comment by hellysmile** [comment]
@ImanYZ yes

**Comment by ImanYZ** [comment]
@hellysmile, Unfortunately this file does not exist on my computer!

**Comment by ImanYZ** [comment]
@hellysmile, I was using fake-useragent for a long time.
My other two computers are still using it without any problem.

This problem happened a couple of weeks ago when I upgraded fake-useragent.

**Comment by chrisspen** [comment]
This just happened to me too on a fresh install of Ubuntu 14.04. Removing that file does not resolve the problem.

```
python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from fake_useragent import UserAgent
>>> ua = UserAgent()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/fake_useragent/fake.py", line 12, in __init__
    self.data = load_cached()
  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 134, in load_cached
    update()
  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 129, in update
    write(load())
  File "/usr/local/myproject/.env/local/lib/python2.7/site-packages/fake_useragent/utils.py", line 88, in load
    for counter in range(int(float(percent))):
ValueError: could not convert string to float: <a
```

**Comment by hellysmile** [comment]
Hey guys, I can not really reproduce it, working fine for me

**Comment by chrisspen** [comment]
I think I found the problem. I still had the 0.0.5 version installed. I think it might be incorrectly packaged, because when I used pip to upgrade to 0.0.7, it kept the 0.0.5 version. I had to manually delete all fake_useragent files from my virtualenv and then re-install to get to 0.0.7, which fixed the problem.

**Comment by hellysmile** [comment]
@chrisspen, thanks will try to figure out what wrong with packing

**Comment by hellysmile** [comment]
I've double checked packing and it seems working fine
