### ISSUE TITLE
how to tell if the fallback agent is used?

### ISSUE THREAD

**Issue by StingyJack** [fake-useragent/fake-useragent#92]
If i specify a fallback value, how can I tell when that is used when `.random` is called?

``` python
import fake_useragent

def get_user_agent() => str:
  fallback = "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36"
  ua = fake_useragent.UserAgent(fallback=fallback)
  return_value = ua.random
  return return_value
```

`fallback` should be a valid user agent and one that _could_ be returned by `ua.random` normally. Currently this code just produces the error described in #62, but the [Pypi page](https://pypi.org/project/fake-useragent/) says 

> You can completely disable ANY annoying exception with adding fallback: (version 0.1.4 added)

So i cant determine if the module is using the fallback I gave to it and just printing the traceback in case I wanted to know there was a problem, or if the examples on pypi are not correct, or if I'm just misunderstanding what they are telling me.  

I want to specify a value to use should the fake useragent source and cache pages be unavailable (which is more often now), so that outgoing requests dont advertise themselves as the python requests library. How do I make sure that is happening?

**Comment by 153957** [comment]
It will still log a warning message when the fallback will be used: https://github.com/hellysmile/fake-useragent/blob/master/fake_useragent/fake.py#L94

The warning is logged during the `load` method which is called by the `__init__`. So before you call `.random`.

**Comment by melroy89** [comment]
Fallback is only used if everything else failed.
