### ISSUE TITLE
the useragent is not matching my OS

### ISSUE THREAD

**Issue by viponedream** [fake-useragent/fake-useragent#96]
from fake_useragent import UserAgent
ua = UserAgent(use_cache_server=False)
print(ua.chrome)
Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36

 (Windows NT 6.1; WOW64)  -->>  does not fit my system.
the  website can find out i'm using a fake useragent.
because he knows i am in windows 10 or linux

**Comment by chr-peters** [comment]
Would be cool if we could set a parameter like `os="windows"` to select the operating system. This parameter could default to the os that is running on the computer if it's not explicitly set by the user.

**Comment by melroy89** [comment]
Fake user-agent by default just gets you a random user agent string (in this case a random chrome user-agent string). Which means it can also be another operating string like Linux.

**Comment by melroy89** [comment]
Upgrade `pip  install --upgrade fake-useragent` to get the latest version. Which should now give you more up to date user agent strings.

Also you have the ability to set `os="windows"` now.

**Comment by roke-julian-lockhart** [comment]
> https://github.com/fake-useragent/fake-useragent/issues/96#issuecomment-1662862564

@melroy89, per @chr-peters's comment

> This parameter could default to the os that is running on the computer if it's not explicitly set by the user.

from https://github.com/fake-useragent/fake-useragent/issues/96#issuecomment-644378273, does it?

**Comment by melroy89** [comment]
You have the ability now to set the OS.

```
from fake_useragent import UserAgent
ua = UserAgent(os='windows')
ua.random
```

Since we don't have a lot of user agent strings, the default is still all OS's.
